var amgDebug=location.search.slice(1).split('&').indexOf('amgdebug=true')!==-1;if(amgDebug){console.log('[amgdebug]');}
var amgInArticle=window.amgInArticle||{config:{AD_UNIT_CODE:'/21622890900/ID_tribunnews.com_res_autoads',AD_SIZES:[[300,250],[300,600],[1,1],[336,280],"fluid"],ARTICLE_NODE_SELECTOR:'.side-article',TARGET_POSITION_PERCENTAGE:90,TARGET_SELECTORS:['p','br','h1','h2','h3','h4','div','figure'],ARTICLE_MIN_HEIGHT:500,GPT_IS_SYNC:0,DISABLE_INITIAL_LOAD:1,DISPLAY_ADVERTISEMENT:0,INNER_TEXT_MIN_LENGTH:5,MARGIN_TOP:0,MARGIN_BOTTOM:0,FULL_WIDTH_AD_SLOT:1,TRACK_COORDINATE:0,ELEMENT_COUNT:0},time:null,articleNode:null,positions:[],slot:null,inArticleWrapper:null,inArticleNode:null,inArticleNodeFrame:null,log:amgDebug?function(){var arr=Array.prototype.slice.call(arguments,0);console.log('====== [amgdebug] ',arr.shift(),'======');console.log.apply(this,arr);}:function(){},_addStyle:function(css){var style=document.createElement('style');style.type='text/css';style.appendChild(document.createTextNode(css));var head=document.head||document.getElementsByTagName('head')[0];head.appendChild(style);},_getArticleNode:function(){console.log(this.config.ARTICLE_NODE_SELECTOR);return document.body.querySelector(this.config.ARTICLE_NODE_SELECTOR);},_getPositions:function(node){var articleNodeSelector=this.config.ARTICLE_NODE_SELECTOR;var innerTextMinLength=this.config.INNER_TEXT_MIN_LENGTH;var selectors=this.config.TARGET_SELECTORS.map(function(value){return articleNodeSelector+'>'+value}).join(',');var innerNodes=node.querySelectorAll(selectors);var positions=Array.prototype.filter.call(innerNodes,function(e){if(e.tagName==='P'){return e.innerText.length>=innerTextMinLength;}else if(e.tagName==='BR'){return e.nextSibling&&e.nextSibling.nodeType===Node.TEXT_NODE&&e.nextSibling.textContent.length>=innerTextMinLength;}
return true});this.log('Article Nodes: ',innerNodes,positions);return positions;},debugPositions:function(){var positions=this.positions;for(var i=0;i<positions.length;i++){this.insertLineBefore(positions[i],i.toString())}},insertLineBefore:function(refNode,text){var lineNode=document.createElement('div');lineNode.style.cssText='width:100%;height:25px;background-color:red;color:white;text-align:center;';if(!!text){lineNode.innerHTML=text;}
refNode.parentNode.insertBefore(lineNode,refNode);},_showAdvertisementText:function(){var inArticleWrapper=this.inArticleWrapper;if(document.getElementById('ad-amg-advertisement-heading-text')){return;}
var inArticleNode=this.inArticleNode;var node=document.createTextNode('ADVERTISEMENT');var advertisement=document.createElement('p');advertisement.id='ad-amg-advertisement-heading-text';advertisement.style.textAlign='center';advertisement.style.color='#8A9299';advertisement.style.fontSize='10px';advertisement.style.marginTop='3px';advertisement.style.marginBottom='3px';advertisement.style.textTransform='uppercase';inArticleNode.style.marginBottom='20px';advertisement.appendChild(node);inArticleWrapper.insertBefore(advertisement,inArticleNode);},_defineAd:function(){var ad_unit_code=this.config.AD_UNIT_CODE;var ad_unit_size=this.config.AD_SIZES;var display_advertisement=this.config.DISPLAY_ADVERTISEMENT;var inArticleWrapper=this.inArticleWrapper;var inArticleNode=this.inArticleNode;var marginTop=this.config.MARGIN_TOP;var marginBottom=this.config.MARGIN_BOTTOM;if(this.config.GPT_IS_SYNC){var frame=this.inArticleNodeFrame=document.createElement('iframe');frame.id='div-gpt-ad-amg-in-article-frame';frame.marginHeight=frame.marginWidth='0';frame.style.cssText='visibility: hidden; height: 0px; width: 0px; border: none; background:transparent;';inArticleNode.appendChild(frame);}else{googletag.cmd.push(function(){var slot=amgInArticle.slot=googletag.defineSlot(ad_unit_code,ad_unit_size,'div-gpt-ad-amg-in-article').addService(googletag.pubads()).setCollapseEmptyDiv(true,true);googletag.enableServices();googletag.pubads().addEventListener('slotRenderEnded',function(event){if(!event.isEmpty&&event.slot===slot){inArticleWrapper.style.display='block';if(event.size[1]===1){inArticleNode.style.height='1px';}else{inArticleWrapper.style.marginTop=marginTop+'px';inArticleWrapper.style.marginBottom=marginBottom+'px';if(display_advertisement){amgInArticle._showAdvertisementText();if(event.size[0]!==0&&event.size[0]!==0){inArticleWrapper.style.borderTop='1px solid #f3f3f3';inArticleWrapper.style.borderBottom='1px solid #f3f3f3';}}}}});});}},_fetchAd:function(){if(this.config.GPT_IS_SYNC){var doc=this.inArticleNodeFrame.contentDocument;doc.open();doc.write('<script src="https://www.googletagservices.com/tag/js/gpt.js">'+
'googletag.pubads().addEventListener("slotRenderEnded", function(event) {'+
'var amgInArticle = window.top.window.amgInArticle;'+
'amgInArticle._fetchAdIFrameCallBack(event.size);'+
'});'+
'googletag.pubads().definePassback("'+this.config.AD_UNIT_CODE+'",[['+this.config.AD_SIZES.join("],[")+']])'+
'.set("page_url", "'+location.href.replace(/https?:\/\//i,"")+'")'+
'.display();'+
'</script>');doc.close();}else{var disable_initial_load=this.config.DISABLE_INITIAL_LOAD;googletag.cmd.push(function(){googletag.display('div-gpt-ad-amg-in-article');if(disable_initial_load){googletag.pubads().refresh([amgInArticle.slot]);}});}},_fetchAdIFrameCallBack:function(size){this.inArticleWrapper.style.display='block';var frame=this.inArticleNodeFrame;frame.width=size[0];frame.height=size[1];frame.style.width=size[0]+'px';frame.style.height=size[1]+'px';frame.style.visibility='visible';var inArticleWrapper=this.inArticleWrapper;if(size[1]!==1){inArticleWrapper.style.marginTop=this.config.MARGIN_TOP+'px';inArticleWrapper.style.marginBottom=this.config.MARGIN_BOTTOM+'px';if(this.config.DISPLAY_ADVERTISEMENT){this._showAdvertisementText();inArticleWrapper.style.borderTop='1px solid #f3f3f3';inArticleWrapper.style.borderBottom='1px solid #f3f3f3';}}},_executeAdSlot:function(articleNode){var articleNodeRect=articleNode.getBoundingClientRect();var articleNodeTop=articleNodeRect.top+window.pageYOffset;var articleNodeHeight=articleNodeRect.height;this.log('articleNodeHeight: ',articleNodeHeight);if(articleNodeHeight<this.config.ARTICLE_MIN_HEIGHT){this.log('This article is too short.');return;}
var targetPositionPercentage=this.config.TARGET_POSITION_PERCENTAGE;var targetHeight=articleNodeTop+articleNodeHeight*(targetPositionPercentage/100);this.log('targetHeight: ',targetHeight);var ref=new Array(4);var positions=this.positions;if(this.positions.length<1){this.log('No positions.');return;}
var node,nodeTop,diff;if(this.config.ELEMENT_COUNT){var targetIndex;if(typeof(this.config.ELEMENT_COUNT)==='number'){targetIndex=this.config.ELEMENT_COUNT;if(!positions[targetIndex]){this.log('No targetIndex:',targetIndex);return}}else{targetIndex=Math.round(this.positions.length*(targetPositionPercentage/100));}
this.log('targetCount',targetIndex);node=positions[targetIndex];nodeTop=node.getBoundingClientRect().top+window.pageYOffset;diff=Math.abs(targetHeight-nodeTop);ref=[targetIndex,node,nodeTop,diff];}else{for(var i=0;i<positions.length;i++){node=positions[i];nodeTop=node.getBoundingClientRect().top+window.pageYOffset;diff=Math.abs(targetHeight-nodeTop);var m=ref[3];if(!m||diff<m){ref=[i,node,nodeTop,diff];}}}
this.log('result:',ref[0],ref[1],ref[2],ref[3]);var refNode=ref[1];if(!refNode){this.log('No refNode!');return;}
this._addStyle('#div-gpt-ad-amg-in-article iframe { margin: 0!important; }');var inArticleWrapper=this.inArticleWrapper=document.createElement('div');inArticleWrapper.id='amg-in-article-wrapper';inArticleWrapper.style.display='none';if(this.config.FULL_WIDTH_AD_SLOT){var left=0;var right=0;if(typeof(this.config.FULL_WIDTH_AD_SLOT)==='number'){left=right=this.config.FULL_WIDTH_AD_SLOT;}else{var refNodeStyle=window.getComputedStyle(refNode);var refNodeRect=refNode.getBoundingClientRect();left=refNodeRect.left+parseFloat(refNodeStyle.paddingLeft);right=refNodeRect.right-refNodeRect.width+parseFloat(refNodeStyle.paddingRight);}
inArticleWrapper.style.marginLeft=-left+'px';inArticleWrapper.style.marginRight=-right+'px';}
var inArticleNode=this.inArticleNode=document.createElement('div');inArticleNode.id='div-gpt-ad-amg-in-article';inArticleNode.style.display='block';inArticleNode.style.textAlign='center';inArticleNode.style.marginLeft='auto';inArticleNode.style.marginRight='auto';inArticleWrapper.appendChild(inArticleNode);refNode.parentNode.insertBefore(inArticleWrapper,refNode);this._defineAd();var trackCoordinate=this.config.TRACK_COORDINATE;if(trackCoordinate){var track=ref[2]-trackCoordinate;var that=this;function step(){that.log(1);if(window.pageYOffset+window.innerHeight>track){that._fetchAd();}else{window.requestAnimationFrame(step);}}
window.requestAnimationFrame(step);}else{this._fetchAd()}},executeInArticleSlot:function(){var startTime=new Date();console.log(this.articleNode);var articleNode=this.articleNode=this._getArticleNode();if(!articleNode){this.log('No article div');return;}
this.log('Article Node',articleNode);this.positions=this._getPositions(articleNode);this._executeAdSlot(articleNode);var endTime=new Date();this.time=endTime-startTime;this.log('executeInArticleSlot finished: ',this.time+'ms');}};var execute=function(){if(amgDebug){amgInArticle.executeInArticleSlot();amgInArticle.debugPositions();}else{try{amgInArticle.executeInArticleSlot();}catch(e){}}};if(document.readyState!=='loading'){execute()}else{document.addEventListener('DOMContentLoaded',execute)}