(function(c,d){function t(c){if(c)return c.replace(/^\s+|\s+$/g,"")}function n(e,d){if(!e)return{};var b="INFO"===d.logLevel;e.m&&e.m.message&&(e=e.m);var h=d.m||d.message||"",h=e.m&&e.m.message?h+e.m.message:e.m&&e.m.target&&e.m.target.tagName?h+("Error handler invoked by "+e.m.target.tagName+" tag"):e.m?h+e.m:e.message?h+e.message:h+"Unknown error",h={m:h,name:e.name,type:e.type,csm:N+" "+(e.fromOnError?"onerror":"ueLogError")},g,m,k=0,n;h.logLevel=d.logLevel||A;d.adb&&(h.adb=d.adb);if(g=d.attribution)h.attribution=
""+g;if(!b){h.pageURL=d.pageURL||""+(window.location?window.location.href:"")||"missing";h.f=e.f||e.sourceURL||e.fileName||e.filename||e.m&&e.m.target&&e.m.target.src;h.l=e.l||e.line||e.lineno||e.lineNumber;h.c=e.c?""+e.c:e.c;h.s=[];h.t=c.ue.d();if((b=e.stack||(e.err?e.err.stack:""))&&b.split)for(h.csm+=" stack",g=b.split("\n");k<g.length&&h.s.length<z;)(b=g[k++])&&h.s.push(t(b));else for(h.csm+=" callee",m=x(e.args||arguments,"callee"),g=k=0;m&&k<z;)n=p,m.skipTrace||(b=m.toString())&&b.substr&&(n=
0===g?4*p:n,n=1==g?2*p:n,h.s.push(b.substr(0,n)),g++),m=x(m,"caller"),k++;if(!h.f&&0<h.s.length&&(k=h)&&k.s){var w,b=0<k.s.length?k.s[0]:"";g=1<k.s.length?k.s[1]:"";b&&(w=b.match(y));w&&3==w.length||!g||(w=g.match(M));w&&3==w.length&&(k.f=w[1],k.l=w[2])}}return h}function x(c,d){try{return c[d]}catch(b){}}function u(e,p){if(e){for(var b=n(e,p),h=(window.ue_err?window.ue_err.errorHandlers:null)||[],g=0;g<h.length;g++)"function"==typeof h[g].handler&&h[g].handler(b);c.ue.log(b,p.channel||m,{nb:1});
"function"===typeof ue_err.elh&&ue_err.elh(e,p);try{if(!e.fromOnError){var u=d.console,k=d.JSON,h="Error logged with the Track\x26Report JS errors API(http://tiny/1covqr6l8/wamazindeClieUserJava): ";if(u){if(k&&k.stringify)try{h+=k.stringify(b)}catch(t){h+="no info provided; converting to string failed"}else h+=b.m;"function"===typeof u.error?u.error(h,b):"function"===typeof u.log&&u.log(h,b)}}}catch(t){}}}function B(e,d){if(e&&!(c.ue_err.ec>c.ue_err.mxe)){c.ue_err.ter.push(e);d=d||{};var b=e.logLevel||
d.logLevel;d.logLevel=b;d.attribution=e.attribution||d.attribution;b&&b!==A&&b!==J&&b!==C&&b!==K||c.ue_err.ec++;b&&b!=A||ue_err.ecf++;u(e,d)}}if(c.ue_err&&(!c.ueLogError||c.ueLogError.isStub)){var m=c.ue_err_chan||"jserr",A="FATAL",J="ERROR",C="WARN",K="DOWNGRADED",N="v5",z=20,p=256,M=/\(?([^\s]*):(\d+):\d+\)?/,y=/.*@(.*):(\d*)/;u.skipTrace=1;n.skipTrace=1;B.skipTrace=1;(function(){if(c.ue_err.erl){var e=c.ue_err.erl.length,d,b;for(d=0;d<e;d++)b=c.ue_err.erl[d],u(b.ex,b.info);ue_err.erl=[]}})();c.ueLogError=
B}})(ue_csm,window);
(function(c,d){function t(a){for(var l={},f,v,q=0;q<a.length;q++)v=a[q],v.r=v.r||b.rid,v.s=v.s||c.ue_sid,f=v.r+v.s+v.m,v.c&&(l[f]||(l[f]=[]),l[f].push(a[q]));return l}function n(a){for(var l=1;l<arguments.length;l++){var f=arguments[l];try{if(f.isSupported)return f.send(a)}catch(b){}}}function x(){if(g.length&&!b.paused){for(var a=0;a<k.length;a++)k[a]();b._flhs+=1;u();n(t(g.splice(0,g.length)),D,F,G)}w=L=0}function u(){p&&B({k:"chk",f:b._flhs,l:b._lpn,s:"full"},"csm")}function B(a,l,f){f=f||{};!c.ue_furl||
0===f.bf&&b.isBF||(a={r:f.r||(b.paused?void 0:b.rid),s:f.s||(b.paused?void 0:c.ue_sid),m:f.m||c.ue_mid,mkt:f.mkt||c.ue_mkt,sn:f.sn||c.ue_sn,c:l,d:a,t:f.t||b.d(),cs:f.c&&c.ue_qsl},b._lpn[l]=(b._lpn[l]||0)+1,f.b?n(t([a]),D,G):f.nb?n(t([a]),D,F,G):f.img||O[l]?n(t([a]),G):f.ff?(g.push(a),x()):f.n?(g.push(a),0===H?x():w||(w=d.setTimeout(x,H))):(g.push(a),L||(L=d.setTimeout(x,Q))))}function m(a,l,f){I++;I==z&&B({m:"Max number of Forester Logs exceeded",f:"forester-client.js",logLevel:"ERROR"},d.ue_err_chan||
"jserr");(I<z||f&&f.il)&&B(a,l,f)}function A(){if(!P){for(var a=0;a<E.length;a++)E[a]();for(a=0;a<k.length;a++)k[a]();b._flhs+=1;u();n(t(g.splice(0,g.length)),D,G);P=!0}}function J(a){var l=e(a);a.reqs&&(l={csmcount:{counter:M,t:0,value:l.length}},l.csmcount.value+=e(l).length,a.reqs.push(l),l=e(a));return l}var C={};(function(){function a(a){return 10>a?"0"+a:a}function l(a){b.lastIndex=0;return b.test(a)?'"'+a.replace(b,function(a){var f=e[a];return"string"===typeof f?f:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+
'"':'"'+a+'"'}function f(a,b){var e,v,h=q,g,r=b[a];r&&"object"===typeof r&&"function"===typeof r.toJSON&&(r=r.toJSON(a));"function"===typeof d&&(r=d.call(b,a,r));switch(typeof r){case "string":return l(r);case "number":return isFinite(r)?String(r):"null";case "boolean":case "null":return String(r);case "object":if(!r)return"null";q+=c;g=[];if("[object Array]"===Object.prototype.toString.apply(r)){b=r.length;for(a=0;a<b;a+=1)g[a]=f(a,r)||"null";v=0===g.length?"[]":q?"[\n"+q+g.join(",\n"+q)+"\n"+h+
"]":"["+g.join(",")+"]";q=h;return v}if(d&&"object"===typeof d)for(b=d.length,a=0;a<b;a+=1)"string"===typeof d[a]&&(e=d[a],(v=f(e,r))&&g.push(l(e)+(q?": ":":")+v));else for(e in r)Object.prototype.hasOwnProperty.call(r,e)&&(v=f(e,r))&&g.push(l(e)+(q?": ":":")+v);v=0===g.length?"{}":q?"{\n"+q+g.join(",\n"+q)+"\n"+h+"}":"{"+g.join(",")+"}";q=h;return v}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(b){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+
1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(a){return this.valueOf()});var b=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,q,c,e={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},d;"function"!==typeof C.stringify&&(C.stringify=function(a,
b,l){var e;c=q="";if("number"===typeof l)for(e=0;e<l;e+=1)c+=" ";else"string"===typeof l&&(c=l);if((d=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return f("",{"":a})})})();var K=function(){function a(b,f){if(null==b)return f.push("!n");if("number"===typeof b)return f.push("!"+b);if("string"===typeof b)return"\\"==b[b.length-1]?f.push("'"+b.replace(/'/g,"\\'")+"u005C'"):f.push("'"+b.replace(/'/g,"\\'")+"'");if("boolean"===typeof b)return f.push(b?
"!t":"!f");if(b instanceof Array){f.push("*");for(var c=0;c<b.length;c++)a(b[c],f);return f.push(")")}if("object"==typeof b){f.push("(");for(c in b)b.hasOwnProperty(c)&&(f.push(c),a(b[c],f));return f.push(")")}return f.push("!n")}return{stringify:function(b){var f=[];a(b,f);return f.join("")}}}(),N=c.ue_qsl||2E3,z=2E3,p=1===window.ue_ddq,M="foresterPayloadSize",y=function(){},e=d.JSON&&d.JSON.stringify||C&&C.stringify,R=K.stringify,b=c.ue||{},K=c.uet||y;(c.uet||y)("bb","ue_frst_v2",{wb:1});var h=
"//"+c.ue_furl+"/1/batch/1/OE/",g=[],E=[],k=[],P=!1,w,L,H=void 0===c.ue_hpfi?1E3:c.ue_hpfi,Q=void 0===c.ue_lpfi?1E4:c.ue_lpfi,O={"scheduled-delivery":1},I=0,F=function(){function a(){if(d.XDomainRequest){var a=new XDomainRequest;a.onerror=y;a.ontimeout=y;a.onprogress=y;a.onload=y;a.timeout=0;return a}if(d.XMLHttpRequest){a=new XMLHttpRequest;if(!("withCredentials"in a))throw"";return a}if(d.ActiveXObject){for(var b=0;b<e.length&&!a;b++)try{a=new ActiveXObject(e[b]),e=[e[b]]}catch(f){}return a}}function l(a){for(var f=
[],e=a[0]||{},l=0;l<a.length;l++){var d={};d[a[l].c]=a[l].d;f.push(d)}return{rid:e.r||b.rid,sid:e.s||c.ue_sid,mid:e.m||c.ue_mid,mkt:e.mkt||c.ue_mkt,sn:e.sn||c.ue_sn,reqs:f}}function f(b){var f=l(b),c=a();if(!c)throw"";c.onerror=function(){for(var a=0;a<b.length;a++)g.push(b[a]);F.isSupported=!1};c.open("POST",h,!0);c.setRequestHeader&&c.setRequestHeader("Content-type","text/plain");f=J(f);c.send(f)}var e="MSXML2.XMLHTTP.6.0 MSXML2.XMLHTTP.5.0 MSXML2.XMLHTTP.4.0 MSXML2.XMLHTTP.3.0 MSXML2.XMLHTTP Microsoft.XMLHTTP".split(" ");
return{send:function(a){for(var b in a)a.hasOwnProperty(b)&&a[b].length&&f(a[b])},buildPOSTBodyLog:l,isSupported:!0}}(),G=function(){return{send:function(a){for(var l in a)if(a.hasOwnProperty(l)){for(var f=a[l],d=f,q={},g,r=0;r<d.length;r++)g=d[r].c,q[g]||(q[g]=[]),q[g].push(d[r]);f=f[0]||{};d=f.sn||c.ue_sn;f=h+(f.m||c.ue_mid)+":"+(f.s||c.ue_sid)+":"+(f.r||b.rid)+(d?":"+d:"");d=[];g=f;var r=[],m=void 0;for(m in q)if(q.hasOwnProperty(m))for(var k=0;k<q[m].length;k++){var p=q[m][k],n=encodeURIComponent((p.cs?
R:e)(p.d));r.push({l:n,t:p.t,p:1,c:m,d:p.cs?"c":"j"})}q=r;r=void 0;m="$";for(p=0;p<q.length;){k=q[p];r!=k.c?(g+=m+k.c+"\x3d",m="\x26",r=k.c):g+=",";var n=g,u=k.d+":",t=k;g=(t.l.match(".{1,"+(N-g.length)+"}[^%]{0,2}")||[])[0]||"";t.l=t.l.substr(g.length);g=n+(u+g+":"+k.t);if(k.l)g+=":"+k.p++ +"_",d.push(g),g=f,m="$",r=0;else if(p++,1!=k.p)for(g+=":"+k.p+"_"+k.p,n=0;n<k.p-1;n++)d[d.length-n-1]+=k.p}d.push(g);f=d;for(d=0;d<f.length;d++)(new Image).src=f[d]}},isSupported:!0}}(),D=function(){return{send:function(a){for(var b in a)if(a.hasOwnProperty(b)){var f=
F.buildPOSTBodyLog(a[b]),f=J(f);if(!navigator.sendBeacon(h,f))throw"";}},isSupported:!!navigator.sendBeacon}}();b._fic=G;b._fac=F;b._fbc=D;b._flq=g;b.sid=b.sid||c.ue_sid;b.mid=b.mid||c.ue_mid;b.furl=b.furl||c.ue_furl;b.sn=b.sn||c.ue_sn;b._flhs=b._flhs||0;b._lpn=b._lpn||{};try{d.amznJQ&&d.amznJQ.declareAvailable&&d.amznJQ.declareAvailable("forester-client"),d.P&&d.P.register&&d.P.register("forester-client",y)}catch(a){c.ueLogError(a,{logLevel:"WARN"})}(function(){b.log&&b.log.isStub&&(b.log.replay(function(a,
b,f){var c=a[2]||{};c.t=b;c.r=f;c.n=1;m(a[0],a[1],c)}),b.onunload.replay(function(a){E.push(a[0])}),b.onflush.replay(function(a){k.push(a[0])}))})();b.log=m;b.log.reset=function(){I=0};b.onunload=function(a){E.push(a)};b.onflush=function(a){k.push(a)};b.attach("beforeunload",A);b.attach("pagehide",A);K("ld","ue_frst_v2",{wb:1})})(ue_csm,window);
ue_csm.ue.exec(function(c,d){var t=function(){},n=function(){return{send:function(c,n){if(n&&c){var m;if(d.XDomainRequest)m=new XDomainRequest,m.onerror=t,m.ontimeout=t,m.onprogress=t,m.onload=t,m.timeout=0;else if(d.XMLHttpRequest){if(m=new XMLHttpRequest,!("withCredentials"in m))throw"";}else m=void 0;if(!m)throw"";m.open("POST",c,!0);m.setRequestHeader&&m.setRequestHeader("Content-type","text/plain");m.send(n)}},isSupported:!0}}(),x=function(){return{send:function(d,n){if(d&&n)if(navigator.sendBeacon(d,
n))c.ue_sbuimp&&c.ue&&c.ue.ssw&&c.ue.ssw("eelsts","scs");else throw"";},isSupported:!!navigator.sendBeacon&&!(d.cordova&&d.cordova.platformId&&"ios"==d.cordova.platformId)}}();c.ue._ajx=n;c.ue._sBcn=x},"Transportation-clients")(ue_csm,window);
ue_csm.ue.exec(function(c,d){function t(){for(var a=0;a<arguments.length;a++){var c=arguments[a];try{var f;if(c.isSupported){var h=D.buildPayload(g,b);f=c.send(e,h)}else throw dummyException;return f}catch(q){}}M({m:"All supported clients failed",attribution:"CSMSushiClient_TRANSPORTATION_FAIL",f:"sushi-client.js",logLevel:"ERROR"},d.ue_err_chan||"jserr")}function n(){if(b.length){for(var a=0;a<H.length;a++)H[a]();t(p._sBcn||{},p._ajx||{});b=[];h={};g={};O=I=E=k=0}}function x(){var a=new Date,b=function(a){return 10>
a?"0"+a:a};return Date.prototype.toISOString?a.toISOString():a.getUTCFullYear()+"-"+b(a.getUTCMonth()+1)+"-"+b(a.getUTCDate())+"T"+b(a.getUTCHours())+":"+b(a.getUTCMinutes())+":"+b(a.getUTCSeconds())+"."+String((a.getUTCMilliseconds()/1E3).toFixed(3)).slice(2,5)+"Z"}function u(a){try{return JSON.stringify(a)}catch(b){}return null}function B(a,e,f,g){var q=!1;g=g||{};w++;w==C&&M({m:"Max number of Sushi Logs exceeded",f:"sushi-client.js",logLevel:"ERROR",attribution:"CSMSushiClient_MAX_CALLS"},d.ue_err_chan||
"jserr");var h;if(h=!(w>=C))(h=a&&-1<a.constructor.toString().indexOf("Object")&&e&&-1<e.constructor.toString().indexOf("String")&&f&&-1<f.constructor.toString().indexOf("String"))||P++;h&&(a.producerId=a.producerId||e,a.schemaId=a.schemaId||f,a.timestamp=x(),e=Date.now?Date.now():+new Date,f=Math.random().toString().substring(2,12),a.messageId=c.ue_id+"-"+e+"-"+f,g&&!g.ssd&&(a.sessionId=a.sessionId||c.ue_sid,a.requestId=a.requestId||c.ue_id,a.obfuscatedMarketplaceId=a.obfuscatedMarketplaceId||c.ue_mid),
(e=u(a))?(e=e.length,(b.length==K||E+e>N)&&n(),E+=e,a={data:D.compressEvent(a)},b.push(a),(g||{}).n?0===F?n():O||(O=d.setTimeout(n,F)):I||(I=d.setTimeout(n,G)),q=!0):q=!1);!q&&c.ue_int&&console.error("Invalid JS Nexus API call");return q}function m(){if(!Q){for(var a=0;a<L.length;a++)L[a]();for(a=0;a<H.length;a++)H[a]();b.length&&(c.ue_sbuimp&&c.ue&&c.ue.ssw&&(a=u({dct:g,evt:b}),c.ue.ssw("eeldata",a),c.ue.ssw("eelsts","unk")),t(p._sBcn||{}));Q=!0}}function A(a){L.push(a)}function J(a){H.push(a)}var C=
1E3,K=499,N=524288,z=function(){},p=c.ue||{},M=p.log||z,y=c.uex||z;(c.uet||z)("bb","ue_sushi_v1",{wb:1});var e=c.ue_surl||"https://unagi-na.amazon.com/1/events/com.amazon.csm.nexusclient.gamma",R=["messageId","timestamp"],b=[],h={},g={},E=0,k=0,P=0,w=0,L=[],H=[],Q=!1,O,I,F=void 0===c.ue_hpsi?1E3:c.ue_hpsi,G=void 0===c.ue_lpsi?1E4:c.ue_lpsi,D=function(){function a(a){h[a]||(h[a]="#"+k++,g[h[a]]=a);return h[a]}function c(a){return a.length>("#"+k).length||"#"===a.charAt(0)}function f(a){if(a)switch(typeof a){case "number":return!(isNaN(a)||
Infinity===a)&&c(a.toString());case "boolean":break;case "string":return c(a);default:return!0}return!1}function e(b){if(f(b)){var c=0;b instanceof Array?c=2:b instanceof Function?c=0:b instanceof Object&&(c=1);switch(c){case 0:b=a(b);break;case 2:var d=b;b=[];for(var c=d.length,g=0;g<c;g++)b[g]=e(d[g]);break;case 1:c={};for(d in b)b.hasOwnProperty(d)&&(c[a(d)]=-1==R.indexOf(d)?e(b[d]):b[d]);b=c}}return b}return{compressEvent:e,buildPayload:function(){return u({cs:{dct:g},events:b})}}}();(function(){if(p.event&&
p.event.isStub){if(c.ue_sbuimp&&c.ue&&c.ue.ssw){var a=c.ue.ssw("eelsts").val;if(a&&"unk"===a&&(a=c.ue.ssw("eeldata").val)){var d;a:{try{d=JSON.parse(a);break a}catch(f){}d=null}d&&d.evt instanceof Array&&d.dct instanceof Object&&(b=d.evt,g=d.dct,b&&g&&(n(),c.ue.ssw("eeldata","{}"),c.ue.ssw("eelsts","scs")))}}p.event.replay(function(a){a[3]=a[3]||{};a[3].n=1;B.apply(this,a)});p.onSushiUnload.replay(function(a){A(a[0])});p.onSushiFlush.replay(function(a){J(a[0])})}})();p.attach("beforeunload",m);p.attach("pagehide",
m);p._cmps=D;p.event=B;p.event.reset=function(){w=0};p.onSushiUnload=A;p.onSushiFlush=J;try{d.P&&d.P.register&&d.P.register("sushi-client",z)}catch(a){c.ueLogError(a,{logLevel:"WARN"})}y("ld","ue_sushi_v1",{wb:1})},"Nxs-JS-Client")(ue_csm,window);