var tracking=tracking||function(){return{}}();
tracking.pulsarjs=tracking.pulsarjs&&void 0===QUnit||function(){return{getPlsUBTBrowser2:function(a){if(void 0==a||null==a)a=navigator.userAgent;for(var a=a?a.toLowerCase().replace(/-/g,""):"",b=["chrome","firefox","safari","msie","opera"],e={name:null,isMobile:!1},d=0;d<b.length;d+=1)if(-1!==a.indexOf(b[d])){e.name=b[d];break}null!=e.name&&(e.isMobile=null!=a.match(/iPhone|iPad|iPod/i));return e},getUnloadEvent:function(a){var b="unload";return b="chrome"==a.name?"beforeunload":"safari"==a.name&&
a.isMobile&&"onpagehide"in window?"pagehide":"safari"==a.name&&!a.isMobile?"beforeunload":"unload"}}}();function BigInteger(a,b){if(!(this instanceof BigInteger))return a instanceof BigInteger?a:"undefined"===typeof a?BigInteger.ZERO:BigInteger.parse(a);for(;a.length&&!a[a.length-1];)--a.length;this._d=a;this._s=a.length?b||1:0}
BigInteger.radixRegex=[/^$/,/^$/,/^[01]*$/,/^[012]*$/,/^[0-3]*$/,/^[0-4]*$/,/^[0-5]*$/,/^[0-6]*$/,/^[0-7]*$/,/^[0-8]*$/,/^[0-9]*$/,/^[0-9aA]*$/,/^[0-9abAB]*$/,/^[0-9abcABC]*$/,/^[0-9a-dA-D]*$/,/^[0-9a-eA-E]*$/,/^[0-9a-fA-F]*$/,/^[0-9a-gA-G]*$/,/^[0-9a-hA-H]*$/,/^[0-9a-iA-I]*$/,/^[0-9a-jA-J]*$/,/^[0-9a-kA-K]*$/,/^[0-9a-lA-L]*$/,/^[0-9a-mA-M]*$/,/^[0-9a-nA-N]*$/,/^[0-9a-oA-O]*$/,/^[0-9a-pA-P]*$/,/^[0-9a-qA-Q]*$/,/^[0-9a-rA-R]*$/,/^[0-9a-sA-S]*$/,/^[0-9a-tA-T]*$/,/^[0-9a-uA-U]*$/,/^[0-9a-vA-V]*$/,/^[0-9a-wA-W]*$/,
/^[0-9a-xA-X]*$/,/^[0-9a-yA-Y]*$/,/^[0-9a-zA-Z]*$/];BigInteger.ZERO=new BigInteger([],0);BigInteger.ONE=new BigInteger([1],1);
BigInteger.small=[BigInteger.ZERO,BigInteger.ONE,new BigInteger([2],1),new BigInteger([3],1),new BigInteger([4],1),new BigInteger([5],1),new BigInteger([6],1),new BigInteger([7],1),new BigInteger([8],1),new BigInteger([9],1),new BigInteger([0,1],1),new BigInteger([1,1],1),new BigInteger([2,1],1),new BigInteger([3,1],1),new BigInteger([4,1],1),new BigInteger([5,1],1),new BigInteger([6,1],1),new BigInteger([7,1],1),new BigInteger([8,1],1),new BigInteger([9,1],1),new BigInteger([0,2],1),new BigInteger([1,
2],1),new BigInteger([2,2],1),new BigInteger([3,2],1),new BigInteger([4,2],1),new BigInteger([5,2],1),new BigInteger([6,2],1),new BigInteger([7,2],1),new BigInteger([8,2],1),new BigInteger([9,2],1),new BigInteger([0,3],1),new BigInteger([1,3],1),new BigInteger([2,3],1),new BigInteger([3,3],1),new BigInteger([4,3],1),new BigInteger([5,3],1),new BigInteger([6,3],1)];BigInteger.digits="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");
BigInteger.prototype.toString=function(a){a=+a||10;if(2>a||36<a)throw Error("illegal radix "+a+".");if(0===this._s)return"0";if(10===a)return(0>this._s?"-":"")+(this._d.slice().reverse().join("")||"0");for(var b=BigInteger.digits,a=BigInteger(a),e=this._s,d=this.abs(),g=[],f;0!==d._s;)f=d.divRem(a),d=f[0],f=f[1],g.push(b[f]);return(0>e?"-":"")+g.reverse().join("")};
BigInteger.parse=function(a,b){a=a.toString();if("undefined"===typeof b||10===+b){var e;e=a.replace(/\s*[*xX]\s*10\s*(\^|\*\*)\s*/,"e");a=e.replace(/^([+\-])?(\d+)\.?(\d*)[eE]([+\-]?\d+)$/,function(a,b,d,e,f){var f=+f,g=0>f,i=d.length+f,a=(g?d:e).length,f=(f=Math.abs(f))>=a?f-a+g:0,a=Array(f+1).join("0"),d=d+e;return(b||"")+(g?d=a+d:d+=a).substr(0,i+=g?a.length:0)+(i<d.length?"."+d.substr(i):"")})}var d=/^([+\-]?)(0[xXbB]?)?([0-9A-Za-z]*)(?:\.\d*)?$/.exec(a);if(d){e=d[1]||"+";var g=d[2]||"",d=d[3]||
"";if("undefined"===typeof b)"0"===g?0===d.length?(b=10,d="0"):b=8:b="0x"===g||"0X"===g?16:"0b"===g||"0B"===g?2:10;else if(2>b||36<b)throw Error("Illegal radix "+b+".");b=+b;if(!BigInteger.radixRegex[b].test(d))throw Error("Bad digit for radix "+b);d=d.replace(/^0+/,"").split("");if(0===d.length)return BigInteger.ZERO;e="-"===e?-1:1;if(10===b){for(var f=d.length,j=Array(f),g=0;g<f;g++)j[g]=Number(d[g]);return new BigInteger(j.reverse(),e)}f=BigInteger.ZERO;b=BigInteger(b);j=BigInteger.small;for(g=
0;g<d.length;g++)f=f.multiply(b).add(j[parseInt(d[g],36)]);return new BigInteger(f._d,e)}throw Error("Invalid BigInteger format: "+a);};
BigInteger.prototype.add=function(a){if(0===this._s)return BigInteger(a);a=BigInteger(a);if(0===a._s)return this;if(this._s!==a._s)return a=a.negate(),this.subtract(a);for(var b=this._d,a=a._d,e=b.length,d=a.length,g=Array(Math.max(e,d)+1),f=Math.min(e,d),j=0,c=0;c<f;c++)j=b[c]+a[c]+j,g[c]=j%10,j=j/10|0;d>e&&(b=a,e=d);for(c=f;j&&c<e;c++)j=b[c]+j,g[c]=j%10,j=j/10|0;for(j&&(g[c]=j);c<e;c++)g[c]=b[c];return new BigInteger(g,this._s)};
BigInteger.prototype.abs=function(){return 0>this._s?this.negate():this};
BigInteger.prototype.subtract=function(a){if(0===this._s)return BigInteger(a).negate();a=BigInteger(a);if(0===a._s)return this;if(this._s!==a._s)return a=a.negate(),this.add(a);var b=this;if(0>this._s)var e=b,b=new BigInteger(a._d,1),a=new BigInteger(e._d,1);var d=b.compareAbs(a);if(0===d)return BigInteger.ZERO;0>d&&(e=a,a=b,b=e);for(var b=b._d,a=a._d,e=b.length,g=a.length,f=Array(e),j=0,c=0;c<g;c++){var m=b[c]-j-a[c];0>m?(m+=10,j=1):j=0;f[c]=m}for(c=g;c<e;c++){m=b[c]-j;if(0>m)m+=10;else{f[c++]=m;
break}f[c]=m}for(;c<e;c++)f[c]=b[c];return new BigInteger(f,d)};
(function(){function a(a,b){for(var g=a._d,f=g.slice(),j=0;;){var c=(g[j]||0)+1;f[j]=c%10;if(9>=c)break;++j}return new BigInteger(f,b)}function b(a,b){for(var g=a._d,f=g.slice(),j=0;;){var c=(g[j]||0)-1;if(0>c)f[j]=c+10;else{f[j]=c;break}++j}return new BigInteger(f,b)}BigInteger.prototype.next=function(){switch(this._s){case 0:return BigInteger.ONE;case -1:return b(this,-1);default:return a(this,1)}};BigInteger.prototype.prev=function(){switch(this._s){case 0:return BigInteger.M_ONE;case -1:return a(this,
-1);default:return b(this,1)}}})();BigInteger.prototype.compareAbs=function(a){if(this===a)return 0;a=BigInteger(a);if(0===this._s)return 0!==a._s?-1:0;if(0===a._s)return 1;var b=this._d.length,e=a._d.length;if(b<e)return-1;if(b>e)return 1;e=this._d;a=a._d;for(b-=1;0<=b;b--)if(e[b]!==a[b])return e[b]<a[b]?-1:1;return 0};BigInteger.prototype.compare=function(a){if(this===a)return 0;a=BigInteger(a);return 0===this._s?-a._s:this._s===a._s?this.compareAbs(a)*this._s:this._s};
BigInteger.prototype.isUnit=function(){return this===BigInteger.ONE||this===BigInteger.M_ONE||1===this._d.length&&1===this._d[0]};
BigInteger.prototype.multiply=function(a){if(0===this._s)return BigInteger.ZERO;a=BigInteger(a);if(0===a._s)return BigInteger.ZERO;if(this.isUnit())return 0>this._s?a.negate():a;if(a.isUnit())return 0>a._s?this.negate():this;if(this===a)return this.square();for(var b=this._d.length>=a._d.length,e=(b?this:a)._d,b=(b?a:this)._d,d=e.length,g=b.length,f=d+g,j=Array(f),c=0;c<f;c++)j[c]=0;for(c=0;c<g;c++){for(var f=0,m=b[c],o=d+c,n=c;n<o;n++){var p=j[n]+m*e[n-c]+f,f=p/10|0;j[n]=p%10|0}f&&(p=j[n]+f,j[n]=
p%10)}return new BigInteger(j,this._s*a._s)};
BigInteger.prototype.multiplySingleDigit=function(a,b){if(0===a||0===this._s)return BigInteger.ZERO;if(1===a)return this;if(b[a])return b[a];if(1===this._d.length){var e=this._d[0]*a;if(9<e)return new BigInteger([e%10|0,e/10|0],1);b[a]=BigInteger.small[e];return b[a]}if(2===a)return b[a]=this.add(this),b[a];if(this.isUnit())return b[a]=BigInteger.small[a],b[a];for(var d=this._d,g=d.length,e=g+1,f=Array(e),j=0;j<e;j++)f[j]=0;for(var c=j=0;c<g;c++)e=a*d[c]+j,j=e/10|0,f[c]=e%10|0;j&&(f[c]=j%10);b[a]=
new BigInteger(f,1);return b[a]};BigInteger.prototype.square=function(){if(0===this._s)return BigInteger.ZERO;if(this.isUnit())return BigInteger.ONE;for(var a=this._d,b=a.length,e=Array(b+b+1),d,g,f,j=0;j<b;j++)f=2*j,d=a[j]*a[j],g=d/10|0,e[f]=d%10,e[f+1]=g;for(j=0;j<b;j++){g=0;f=2*j+1;for(var c=j+1;c<b;c++,f++)d=2*a[c]*a[j]+e[f]+g,g=d/10|0,e[f]=d%10;f=b+j;d=g+e[f];g=d/10|0;e[f]=d%10;e[f+1]+=g}return new BigInteger(e,1)};BigInteger.prototype.divide=function(a){return this.divRem(a)[0]};
BigInteger.prototype.remainder=function(a){return this.divRem(a)[1]};
BigInteger.prototype.divRem=function(a){a=BigInteger(a);if(0===a._s)throw Error("Divide by zero");if(0===this._s)return[BigInteger.ZERO,BigInteger.ZERO];if(1===a._d.length)return this.divRemSmall(a._s*a._d[0]);switch(this.compareAbs(a)){case 0:return[this._s===a._s?BigInteger.ONE:BigInteger.M_ONE,BigInteger.ZERO];case -1:return[BigInteger.ZERO,this]}var b=this._s*a._s,e=a.abs(),d=Array(10),g=this._d.slice(),f=[],j=new BigInteger([],1);for(j._s=1;g.length;)if(j._d.unshift(g.pop()),j=new BigInteger(j._d,
1),0>j.compareAbs(a))f.push(0);else{var c=0===j._s?0:9;do{var m=e.multiplySingleDigit(c,d);if(0>=m.compareAbs(j))break;c--}while(c);f.push(c);c&&(c=j.subtract(m),j._d=c._d.slice())}return[new BigInteger(f.reverse(),b),new BigInteger(j._d,this._s)]};
BigInteger.prototype.divRemSmall=function(a){a=+a;if(0===a)throw Error("Divide by zero");var b=this._s*(0>a?-1:1),a=Math.abs(a);if(1>a||9<a)throw Error("Argument out of range");if(0===this._s)return[BigInteger.ZERO,BigInteger.ZERO];if(1===a||-1===a)return[1===b?this.abs():new BigInteger(this._d,b),BigInteger.ZERO];if(1===this._d.length){var e=BigInteger.small[this._d[0]/a|0],a=BigInteger.small[this._d[0]%a|0];0>b&&(e=e.negate());0>this._s&&(a=a.negate());return[e,a]}for(var d=this._d.slice(),e=Array(d.length),
g=0,f=0,j=0;d.length;)if(g=10*g+d[d.length-1],g<a)e[j++]=0,d.pop(),f=10*f+g;else{var c=0===g?0:g/a|0,f=g-a*c;(e[j++]=c)?(d.pop(),g=f):d.pop()}a=BigInteger.small[f];0>this._s&&(a=a.negate());return[new BigInteger(e.reverse(),b),a]};BigInteger.prototype.isOdd=function(){var a=this._d;return!(0===this._s||0===a.length||0===a[0]%2)};BigInteger.prototype.sign=function(){return this._s};BigInteger.prototype.isPositive=function(){return 0<this._s};BigInteger.prototype.isNegative=function(){return 0>this._s};
BigInteger.prototype.modPow=function(a,b){for(var e=BigInteger.ONE,d=this;a.isPositive();)a.isOdd()&&(e=e.multiply(d).remainder(b)),a=a.divide(BigInteger.small[2]),a.isPositive()&&(d=d.square().remainder(b));return e};BigInteger.prototype.valueOf=function(){return parseInt(this.toString(),10)};BigInteger.MAX_EXP=BigInteger(2147483647);
function MD5Hash(a){function b(a,b){var c,d,e,f,g;e=a&2147483648;f=b&2147483648;c=a&1073741824;d=b&1073741824;g=(a&1073741823)+(b&1073741823);return c&d?g^2147483648^e^f:c|d?g&1073741824?g^3221225472^e^f:g^1073741824^e^f:g^e^f}function e(a,c,d,e,f,g,h){a=b(a,b(b(c&d|~c&e,f),h));return b(a<<g|a>>>32-g,c)}function d(a,c,d,e,f,g,h){a=b(a,b(b(c&e|d&~e,f),h));return b(a<<g|a>>>32-g,c)}function g(a,c,d,e,f,g,h){a=b(a,b(b(c^d^e,f),h));return b(a<<g|a>>>32-g,c)}function f(a,c,d,e,f,g,h){a=b(a,b(b(d^(c|~e),
f),h));return b(a<<g|a>>>32-g,c)}function j(a){var b="",c="",d;for(d=0;3>=d;d++)c=a>>>8*d&255,c="0"+c.toString(16),b+=c.substr(c.length-2,2);return b}var c=[],m,o,n,p,h,i,k,l,c=a.replace(/\r\n/g,"\n");m="";for(o=0;o<c.length;o++)n=c.charCodeAt(o),128>n?m+=String.fromCharCode(n):(127<n&&2048>n?m+=String.fromCharCode(n>>6|192):(m+=String.fromCharCode(n>>12|224),m+=String.fromCharCode(n>>6&63|128)),m+=String.fromCharCode(n&63|128));string=m;c=a.length;m=c+8;o=16*((m-m%64)/64+1);n=Array(o-1);for(h=p=
0;h<c;)m=(h-h%4)/4,p=8*(h%4),n[m]|=a.charCodeAt(h)<<p,h++;m=(h-h%4)/4;n[m]|=128<<8*(h%4);n[o-2]=c<<3;n[o-1]=c>>>29;c=n;h=1732584193;i=4023233417;k=2562383102;l=271733878;for(a=0;a<c.length;a+=16)m=h,o=i,n=k,p=l,h=e(h,i,k,l,c[a+0],7,3614090360),l=e(l,h,i,k,c[a+1],12,3905402710),k=e(k,l,h,i,c[a+2],17,606105819),i=e(i,k,l,h,c[a+3],22,3250441966),h=e(h,i,k,l,c[a+4],7,4118548399),l=e(l,h,i,k,c[a+5],12,1200080426),k=e(k,l,h,i,c[a+6],17,2821735955),i=e(i,k,l,h,c[a+7],22,4249261313),h=e(h,i,k,l,c[a+8],7,
1770035416),l=e(l,h,i,k,c[a+9],12,2336552879),k=e(k,l,h,i,c[a+10],17,4294925233),i=e(i,k,l,h,c[a+11],22,2304563134),h=e(h,i,k,l,c[a+12],7,1804603682),l=e(l,h,i,k,c[a+13],12,4254626195),k=e(k,l,h,i,c[a+14],17,2792965006),i=e(i,k,l,h,c[a+15],22,1236535329),h=d(h,i,k,l,c[a+1],5,4129170786),l=d(l,h,i,k,c[a+6],9,3225465664),k=d(k,l,h,i,c[a+11],14,643717713),i=d(i,k,l,h,c[a+0],20,3921069994),h=d(h,i,k,l,c[a+5],5,3593408605),l=d(l,h,i,k,c[a+10],9,38016083),k=d(k,l,h,i,c[a+15],14,3634488961),i=d(i,k,l,h,
c[a+4],20,3889429448),h=d(h,i,k,l,c[a+9],5,568446438),l=d(l,h,i,k,c[a+14],9,3275163606),k=d(k,l,h,i,c[a+3],14,4107603335),i=d(i,k,l,h,c[a+8],20,1163531501),h=d(h,i,k,l,c[a+13],5,2850285829),l=d(l,h,i,k,c[a+2],9,4243563512),k=d(k,l,h,i,c[a+7],14,1735328473),i=d(i,k,l,h,c[a+12],20,2368359562),h=g(h,i,k,l,c[a+5],4,4294588738),l=g(l,h,i,k,c[a+8],11,2272392833),k=g(k,l,h,i,c[a+11],16,1839030562),i=g(i,k,l,h,c[a+14],23,4259657740),h=g(h,i,k,l,c[a+1],4,2763975236),l=g(l,h,i,k,c[a+4],11,1272893353),k=g(k,
l,h,i,c[a+7],16,4139469664),i=g(i,k,l,h,c[a+10],23,3200236656),h=g(h,i,k,l,c[a+13],4,681279174),l=g(l,h,i,k,c[a+0],11,3936430074),k=g(k,l,h,i,c[a+3],16,3572445317),i=g(i,k,l,h,c[a+6],23,76029189),h=g(h,i,k,l,c[a+9],4,3654602809),l=g(l,h,i,k,c[a+12],11,3873151461),k=g(k,l,h,i,c[a+15],16,530742520),i=g(i,k,l,h,c[a+2],23,3299628645),h=f(h,i,k,l,c[a+0],6,4096336452),l=f(l,h,i,k,c[a+7],10,1126891415),k=f(k,l,h,i,c[a+14],15,2878612391),i=f(i,k,l,h,c[a+5],21,4237533241),h=f(h,i,k,l,c[a+12],6,1700485571),
l=f(l,h,i,k,c[a+3],10,2399980690),k=f(k,l,h,i,c[a+10],15,4293915773),i=f(i,k,l,h,c[a+1],21,2240044497),h=f(h,i,k,l,c[a+8],6,1873313359),l=f(l,h,i,k,c[a+15],10,4264355552),k=f(k,l,h,i,c[a+6],15,2734768916),i=f(i,k,l,h,c[a+13],21,1309151649),h=f(h,i,k,l,c[a+4],6,4149444226),l=f(l,h,i,k,c[a+11],10,3174756917),k=f(k,l,h,i,c[a+2],15,718787259),i=f(i,k,l,h,c[a+9],21,3951481745),h=b(h,m),i=b(i,o),k=b(k,n),l=b(l,p);this.md5=(j(h)+j(i)+j(k)+j(l)).toLowerCase();this.get16Bits=function(){for(var a="",b=0;8>
b;b++)a+=this.md5.substr(14-2*b,2);return a}}
var _PlsrCookieUtil={readCookie:function(a){for(var a=a+"=",b=document.cookie.split(";"),e=0;e<b.length;e++){for(var d=b[e];" "==d.charAt(0);)d=d.substring(1);if(0==d.indexOf(a))return d.substring(a.length,d.length)}return""},writeCookie:function(a,b,e){var d=new Date;d.setTime(d.getTime()+864E5*e);e="expires="+d.toUTCString();document.cookie=a+"="+b+"; "+e}},CGuidHash={_guidHash:void 0,getMod1000:function(){if("undefined"==typeof this._guidHash){var a=_plsUBTCookies.readCookie("npii","cguid");0<
a.length&&(a=(new MD5Hash(a)).get16Bits(),this._guidHash=BigInteger.parse(a,16).modPow(BigInteger.ONE,1E3))}return this._guidHash},isInSampling:function(a){if(100==a)return!0;var b=CGuidHash.getMod1000(),a=Math.floor(parseFloat(10*a));return 0>b||b>=a?!1:!0}},JSON=JSON||{};
JSON.stringify=JSON.stringify||function(a){var b=typeof a;if("object"!=b||null===a)return"string"==b&&(a='"'+a+'"'),String(a);var e,d,g=[],f=a&&a.constructor==Array;for(e in a)d=a[e],b=typeof d,"function"!=b&&("string"==b?d='"'+d+'"':"object"==b&&(d=JSON.stringify(d)),g.push((f?"":'"'+e+'":')+String(d)));return(f?"[":"{")+String(g)+(f?"]":"}")};var _plsUBTCookies;"undefined"!==typeof _plsUBTCookiesObj?_plsUBTCookies=new _plsUBTCookiesObj:"undefined"!==typeof raptor&&(_plsUBTCookies=raptor.require("ebay.cookies"));
function TrackingQueue(){this.getLength=function(a){return a.length-0};this.isEmpty=function(a){return 0==a.length};this.pop=function(a,b){var e=a.getLength(b),d=0;if(_plsubtInp.isInSampling)for(d=0;d<e;d++){var g=b[d];"trackImp"==g[0]&&trackImpression();if("clkThr"==g[0]||"inPage"==g[0]||"exit"==g[0]){var f=new _plsLinkClickInp;isNaN(g[1])&&-1<g[1].indexOf("www.")?f.lurl=g[1]:f.lnk=g[1];f.clkType=g[0];f.eventOrder=d;f.difTS=g[2];_plsUBTpld.push(f)}"MSOV"==g[0]&&(f=new _plsLinkMOInp,isNaN(g[1])&&
-1<g[1].indexOf("www.")?f.lurl=g[1]:f.lnk=g[1],f.eventOrder=d,f.difTS=g[2],_plsUBTpld.push(f));"customEvts"==g[0]&&(f=new _plsCustomEventsInp,f.ef=g[1],f.ea=g[2],f.eventOrder=d,f=mergeJSONObjectPlsUBT(f,g[3]),f.difTS=g[4],_plsUBTpld.push(f))}b.splice(0,e)}}_plsUBTTQ.push=function(){var a=arguments[0];"trackImp"!=a[0]&&a.push((new Date).getTime());return Array.prototype.push.apply(this,arguments)};
getplsUBTAllReq=function(){return void 0==_plsubtInp.pageId||0==_plsubtInp.pageId?(console.error("pageId is not available in _plsubtInp."),!1):!0};var plsUBTAllReq=getplsUBTAllReq();
trackImpression=function(){var a={plsUBT:_plsubtInp.plsUBT,ea:"VIEW",pge:_plsubtInp.pageId,app:_plsubtInp.app,scrv:_plsubtInp.resolut,scrColDep:_plsubtInp.scrColDep,tiZone:_plsubtInp.tiZone,sampRate:_plsubtInp.samplingRate,steSpd:_plsubtInp.steSpd},a=mergeJSONObjectPlsUBT(a,_plsubtInp.customAttribute);!_plsubtInp.disableImp&&(_plsubtInp.isInSampling&&plsUBTAllReq)&&(a=_plsubtInp.URLTemplate+"pld="+encodeURIComponent("["+JSON.stringify(a)+"]"),(new Image).src=a)};
var _plsLinkClickInp=function(){return{ea:"CLCK",lnk:"",pge:_plsubtInp.pageId,clkType:"",plsUBT:1,lurl:"",app:_plsubtInp.app,eventOrder:0,difTS:0}},_plsUBTpld=[],_plsLinkMOInp=function(){return{ea:"HOVR",lnk:"",pge:_plsubtInp.pageId,plsUBT:1,lurl:"",app:_plsubtInp.app,difTS:0,eventOrder:0}},_plsCustomEventsInp=function(){return{ef:"",ea:"",pge:_plsubtInp.pageId,plsUBT:1,app:_plsubtInp.app,callingEF:_plsubtInp.eventFamily,difTS:0,eventOrder:0}};
_plsubtInp.samplingRate=null==_plsubtInp.samplingRate?5:_plsubtInp.samplingRate;_plsubtInp.env=null==_plsubtInp.env?"PROD":_plsubtInp.env;_plsubtInp.disableImp=null==_plsubtInp.disableImp?!1:_plsubtInp.disableImp;null==_plsubtInp.eventFamily&&(_plsubtInp.eventFamily="DFLT");getPlsUBTBrowser=function(a){return tracking.pulsarjs.getPlsUBTBrowser2(a).name};_plsubtInp.browser=getPlsUBTBrowser();_plsubtInp.browser2=tracking.pulsarjs.getPlsUBTBrowser2();_plsubtInp.plsUBT=1;
_plsubtInp.resolut=screen.width+"x"+screen.height;_plsubtInp.scrColDep=screen.colorDepth;_plsubtInp.tiZone=((new Date).getTimezoneOffset()/60).toString();isPlsUBTInSampling=function(){var a=!1;if(0!=_plsubtInp.samplingRate)try{a=CGuidHash.isInSampling(_plsubtInp.samplingRate)?!0:!1}catch(b){isInSampg=!0}return a};_plsubtInp.isInSampling=isPlsUBTInSampling();String.prototype.endsWith=function(a){return-1!==this.indexOf(a,this.length-a.length)};
mergeJSONObjectPlsUBT=function(a,b){for(var e in b)a[e]=b[e];return a};
function PlsUBTURLTemplate(a,b,e){var d="";if(null!=a.serverUrl)d=a.serverUrl;else{var g,f="qa"==a.env||-1<b.indexOf(".qa."),j="preprod"==a.env||-1<b.indexOf(".pp.");if(f||j){var c=null;f?(g="www.pulsar.stratus.qa.ebay.com",c="qa"):j&&(g="www.pulsproxy.pp.stratus.ebay.com",c="pp");for(var m="at au be ca ch cn cz de dk es fi fr gr hk hu ie in it my nl no ph pl pt ru sg th uk".split(" "),d=0;d<m.length;d++){var o=m[d];if(-1<b.indexOf("."+o+".")){f?g="www."+o+".pulsar.stratus."+c+".ebay.com":j&&(g="www."+
o+".pulsproxy."+c+".stratus.ebay.com");break}}}else{g="pulsar.ebay.com";f="ebay.com.au ebay.at benl.ebay.be befr.ebay.be cafr.ebay.ca ebay.ca ebay.fr ebay.de ebay.com.cn ebay.com.hk ebay.in ebay.ie ebay.it ebay.com.my ebay.nl ebay.ph ebay.pl ebay.com.sg ebay.es ebay.ch ebay.co.th ebay.co.uk ebay.vn".split(" ");for(d=0;d<f.length;d++)if(j=f[d],b.endsWith(j)){g="pulsar."+j;break}}d=null!=a.https&&!0==a.https?"https://"+g:e+"//"+g}return d=d+"/plsr/mpe/0/"+a.eventFamily+"/9?"}
_plsubtInp.URLTemplate=PlsUBTURLTemplate(_plsubtInp,window.location.hostname,window.location.protocol);steSpdPlsUBT=function(){var a="";null!=_plsubtInp.pageLoadTime&&""!=_plsubtInp.pageLoadTime&&0<_plsubtInp.pageLoadTime?a=(new Date).getTime()-_plsubtInp.pageLoadTime:null!=window.performance.timing&&(a=window.performance.timing.connectEnd-window.performance.timing.connectStart);return a};_plsubtInp.steSpd=steSpdPlsUBT();window._plsUBTTQ.push(["trackImp"]);_plsUBTtaq=new TrackingQueue;
_plsUBTtaq.pop(_plsUBTtaq,window._plsUBTTQ);var _plsUBTPPURL="";function sendBeacon(a){return navigator.sendBeacon?(navigator.sendBeacon(a,""),!0):!1}
function firePulsarProxyURL(a){_plsUBTPPURL=_plsubtInp.URLTemplate+"pld=";var b="[";plsUBTDebug("Initial event queue size: "+_plsUBTpld.length);for(var e=0;e<_plsUBTpld.length;e++)_plsUBTpld[e].difTS=(new Date).getTime()-_plsUBTpld[e].difTS,b+=JSON.stringify(_plsUBTpld[e]),e!=_plsUBTpld.length-1&&(b+=", ");_plsUBTPPURL+=encodeURIComponent(b+"]");plsUBTDebug("Call URL: "+_plsUBTPPURL);"safari"!=_plsubtInp.browser2.name&&navigator.sendBeacon?sendBeacon(_plsUBTPPURL):plsUBTAjaxCall(a)}
firePulsarProxyURLAsImg=function(){for(var a=0;a<_plsUBTpld.length;a++){_plsUBTpld[a].difTS=(new Date).getTime()-_plsUBTpld[a].difTS;var b=_plsubtInp.URLTemplate+"pld="+encodeURIComponent("["+JSON.stringify(_plsUBTpld[a])+"]");(new Image).src=b}};
function postPlsUBTCALL(a){_plsubtInp.isInSampling&&plsUBTAllReq&&(_plsUBTtaq.pop(_plsUBTtaq,window._plsUBTTQ),0!=_plsUBTpld.length&&(firePulsarProxyURL(a),plsUBTDebug("Setting event queue size to 0."),_plsUBTpld.length=0,plsUBTDebug("Final event queue size: "+_plsUBTpld.length)))}function sendWait(a){return void 0==a||null==a||void 0==a.sendWait||null==a.sendWait||isNaN(a.sendWait)?6E4:1E4>a.sendWait?1E4:a.sendWait}
window.addEventListener(tracking.pulsarjs.getUnloadEvent(_plsubtInp.browser2),function(){_unloadAppCallbackHandler.invokeCallbacks();postPlsUBTCALL(!0)});setInterval(function(){postPlsUBTCALL(!1)},sendWait(_plsubtInp));
function plsUBTAjaxCall(a){var b=null;window.XDomainRequest&&(b=new window.XDomainRequest);null==b&&(b=window.XMLHttpRequest?new window.XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP"));var e=_plsUBTPPURL+"&cache="+Math.random();"withCredentials"in b?(b.withCredentials=!0,b.open("POST",e,a?!1:!0),("chrome"==_plsubtInp.browser2.name||"safari"==_plsubtInp.browser2.name)&&b.setRequestHeader("Content-type","application/x-www-form-urlencoded"),b.send("")):(new Image).src=e}
function plsUBTDebug(a){_plsubtInp.debug&&console.log(a)}function AppCallbackHandler(){this.callbacks=[];this.registerCallback=function(a){this.callbacks.push(a)};this.clearCallbacks=function(){this.callbacks=[]};this.invokeCallbacks=function(){this.callbacks.forEach(function(a){try{a()}catch(b){}});this.clearCallbacks()}}var _unloadAppCallbackHandler=new AppCallbackHandler;_plsubtInp.registerUnloadCallback=function(a){_unloadAppCallbackHandler.registerCallback(a)};