/*
Copyright 2014, KISSY v1.49.10
MIT Licensed
build time: Dec 10 15:04
*/
KISSY.add("node/base",["dom","event/dom"],function(b,e){function c(f,m,g){if(!(this instanceof c))return new c(f,m,g);if(f)if("string"===typeof f){if(f=h.create(f,m,g),f.nodeType===k.DOCUMENT_FRAGMENT_NODE)return d.apply(this,a(f.childNodes)),this}else{if(b.isArray(f)||j(f))return d.apply(this,a(f)),this}else return this;this[0]=f;this.length=1;return this}var h=e("dom"),i=e("event/dom"),g=Array.prototype,l=g.slice,k=h.NodeType,d=g.push,a=b.makeArray,j=h.isDomNodeList;c.prototype={constructor:c,isNodeList:!0,
length:0,item:function(f){return"number"===typeof f?f>=this.length?null:new c(this[f]):new c(f)},add:function(f,a,b){"number"===typeof a&&(b=a,a=void 0);f=c.all(f,a).getDOMNodes();a=new c(this);void 0===b?d.apply(a,f):(b=[b,0],b.push.apply(b,f),g.splice.apply(a,b));return a},slice:function(){return new c(l.apply(this,arguments))},getDOMNodes:function(){return l.call(this)},each:function(a,d){var k=this;b.each(k,function(b,j){b=new c(b);return a.call(d||b,b,j,k)});return k},getDOMNode:function(){return this[0]},
end:function(){return this.__parent||this},filter:function(a){return new c(h.filter(this,a))},all:function(a){a=0<this.length?c.all(a,this):new c;a.__parent=this;return a},one:function(a){a=this.all(a);if(a=a.length?a.slice(0,1):null)a.__parent=this;return a}};b.mix(c,{all:function(a,d){return"string"===typeof a&&(a=b.trim(a))&&3<=a.length&&b.startsWith(a,"<")&&b.endsWith(a,">")?(d&&(d.getDOMNode&&(d=d[0]),d=d.ownerDocument||d),new c(a,void 0,d)):new c(h.query(a,d))},one:function(a,d){var b=c.all(a,
d);return b.length?b.slice(0,1):null}});c.NodeType=k;c.KeyCode=i.KeyCode;c.Gesture=i.Gesture;c.REPLACE_HISTORY=i.REPLACE_HISTORY;return c});
KISSY.add("node/attach",["dom","event/dom","./base"],function(b,e){function c(d,a,b){b.unshift(a);d=h[d].apply(h,b);return void 0===d?a:d}var h=e("dom"),i=e("event/dom"),g=e("./base"),l=g.prototype,k=b.makeArray;g.KeyCode=i.KeyCode;b.each("nodeName,isCustomDomain,getEmptyIframeSrc,equals,contains,index,scrollTop,scrollLeft,height,width,innerHeight,innerWidth,outerHeight,outerWidth,addStyleSheet,appendTo,prependTo,insertBefore,before,after,insertAfter,test,hasClass,addClass,removeClass,replaceClass,toggleClass,removeAttr,hasAttr,hasProp,scrollIntoView,remove,empty,removeData,hasData,unselectable,wrap,wrapAll,replaceWith,wrapInner,unwrap".split(","),function(d){l[d]=
function(){var a=k(arguments);return c(d,this,a)}});b.each("getWindow,getDocument,filter,first,last,parent,closest,next,prev,clone,siblings,contents,children".split(","),function(d){l[d]=function(){var a=k(arguments);a.unshift(this);a=h[d].apply(h,a);return a===void 0?this:a===null?null:new g(a)}});b.each({attr:1,text:0,css:1,style:1,val:0,prop:1,offset:0,html:0,outerHTML:0,outerHtml:0,data:1},function(d,a){l[a]=function(){var j;j=k(arguments);void 0===j[d]&&!b.isObject(j[0])?(j.unshift(this),j=h[a].apply(h,
j)):j=c(a,this,j);return j}});b.each(["on","detach","delegate","undelegate"],function(d){l[d]=function(){var a=k(arguments);a.unshift(this);i[d].apply(i,a);return this}});b.each(["fire","fireHandler"],function(d){l[d]=function(){var a=k(arguments);a.unshift(this);return i[d].apply(i,a)}})});
KISSY.add("node/override",["dom","./base","./attach"],function(b,e){var c=e("dom"),h=e("./base");e("./attach");var i=h.prototype;b.each(["append","prepend","before","after"],function(b){i[b]=function(e){"object"!==typeof e&&(e=c.create(e+""));if(e)c[b](e,this);return this}});b.each(["wrap","wrapAll","replaceWith","wrapInner"],function(b){var c=i[b];i[b]=function(b){"string"===typeof b&&(b=h.all(b,this[0].ownerDocument));return c.call(this,b)}})});
KISSY.add("node/anim",["./base","dom","anim"],function(b,e){function c(b,d,a){for(var c=[],f={},a=a||0;a<d;a++)c.push.apply(c,l[a]);for(a=0;a<c.length;a++)f[c[a]]=b;return f}var h=e("./base"),i=e("dom"),g=e("anim"),l=[["height","margin-top","margin-bottom","padding-top","padding-bottom"],["width","margin-left","margin-right","padding-left","padding-right"],["opacity"]];b.augment(h,{animate:function(){var c=b.makeArray(arguments);b.each(this,function(d){var a=b.clone(c),e=a[0];e.to?(e.node=d,(new g(e)).run()):
g.apply(void 0,[d].concat(a)).run()});return this},stop:function(c,d,a){b.each(this,function(b){g.stop(b,c,d,a)});return this},pause:function(c,d){b.each(this,function(a){g.pause(a,d)});return this},resume:function(c,d){b.each(this,function(a){g.resume(a,d)});return this},isRunning:function(){for(var b=0;b<this.length;b++)if(g.isRunning(this[b]))return!0;return!1},isPaused:function(){for(var b=0;b<this.length;b++)if(g.isPaused(this[b]))return!0;return!1}});b.each({show:c("show",3),hide:c("hide",3),
toggle:c("toggle",3),fadeIn:c("show",3,2),fadeOut:c("hide",3,2),fadeToggle:c("toggle",3,2),slideDown:c("show",1),slideUp:c("hide",1),slideToggle:c("toggle",1)},function(c,d){h.prototype[d]=function(a,e,f){if(i[d]&&!a)i[d](this);else b.each(this,function(b){(new g(b,c,a,f,e)).run()});return this}})});
KISSY.add("node",["node/base","node/attach","node/override","node/anim"],function(b,e){var c=e("node/base");e("node/attach");e("node/override");e("node/anim");b.mix(b,{Node:c,NodeList:c,one:c.one,all:c.all});return c});
/*
Copyright 2014, KISSY v1.49.10
MIT Licensed
build time: Dec 10 14:46
*/
KISSY.add("anim",["anim/base","anim/timer","anim/transition?"],function(b,g){function a(a,e,d,f,c){if(a.node)c=a;else{"string"===typeof e?(e=b.unparam(""+e,";",":"),b.each(e,function(c,a){var d=b.trim(a);d&&(e[d]=b.trim(c));(!d||d!==a)&&delete e[a]})):e=b.clone(e);if(b.isPlainObject(d))c=b.clone(d);else if(c={complete:c},d&&(c.duration=d),f)c.easing=f;c.node=a;c.to=e}c=b.merge(k,c,{useTransition:b.config("anim/useTransition")});return c.useTransition&&h?new h(c):new i(c)}var j=g("anim/base"),i=g("anim/timer"),
h=g("anim/transition?"),f=j.Utils,k={duration:1,easing:"linear"};b.each(["pause","resume"],function(b){a[b]=function(a,d){return null===d||"string"===typeof d||!1===d?f.pauseOrResumeQueue(a,d,b):f.pauseOrResumeQueue(a,void 0,b)}});a.isRunning=f.isElRunning;a.isPaused=f.isElPaused;a.stop=f.stopEl;a.Easing=i.Easing;b.Anim=a;a.Q=j.Q;return a});
/*
Copyright 2014, KISSY v1.49.10
MIT Licensed
build time: Dec 10 14:46
*/
KISSY.add("anim/base/queue",["dom"],function(c,i){function h(a,b,c){var b=b||f,j,m=d.data(a,g);!m&&!c&&d.data(a,g,m={});m&&(j=m[b],!j&&!c&&(j=m[b]=[]));return j}var d=i("dom"),g=c.guid("ks-queue-"+c.now()+"-"),f=c.guid("ks-queue-"+c.now()+"-"),a;return a={queueCollectionKey:g,queue:function(a,c,d){a=h(a,c);a.push(d);return a},remove:function(e,b,d){var j=h(e,b,1);j&&(d=c.indexOf(d,j),-1<d&&j.splice(d,1));j&&!j.length&&a.clearQueue(e,b);return j},clearQueues:function(a){d.removeData(a,g)},clearQueue:function(a,
b){var b=b||f,l=d.data(a,g);l&&delete l[b];c.isEmptyObject(l)&&d.removeData(a,g)},dequeue:function(c,b){var d=h(c,b,1);d&&(d.shift(),d.length||a.clearQueue(c,b));return d}}});
KISSY.add("anim/base/utils",["./queue","dom"],function(c,i){var h=i("./queue"),d=i("dom"),g=c.guid("ks-anim-unqueued-"+c.now()+"-"),f=c.guid("ks-anim-paused-"+c.now()+"-");return{saveRunningAnim:function(a){var e=a.node,b=d.data(e,g);b||d.data(e,g,b={});b[c.stamp(a)]=a},removeRunningAnim:function(a){var e=a.node,b=d.data(e,g);b&&(delete b[c.stamp(a)],c.isEmptyObject(b)&&d.removeData(e,g))},isAnimPaused:function(a){var e=d.data(a.node,f);return e?!!e[c.stamp(a)]:0},removePausedAnim:function(a){var e=
a.node,b=d.data(e,f);b&&(delete b[c.stamp(a)],c.isEmptyObject(b)&&d.removeData(e,f))},savePausedAnim:function(a){var e=a.node,b=d.data(e,f);b||d.data(e,f,b={});b[c.stamp(a)]=a},isAnimRunning:function(a){var e=d.data(a.node,g);return e?!!e[c.stamp(a)]:0},isElPaused:function(a){return(a=d.data(a,f))&&!c.isEmptyObject(a)},isElRunning:function(a){return(a=d.data(a,g))&&!c.isEmptyObject(a)},pauseOrResumeQueue:function(a,e,b){a=d.data(a,"resume"===b?f:g);a=c.merge(a);c.each(a,function(a){if(void 0===e||
a.config.queue===e)a[b]()})},stopEl:function(a,e,b,f){b&&(void 0===f?h.clearQueues(a):!1!==f&&h.clearQueue(a,f));a=d.data(a,g);a=c.merge(a);c.each(a,function(a){(void 0===f||a.config.queue===f)&&a.stop(e)})}}});
KISSY.add("anim/base",["dom","./base/utils","./base/queue","promise"],function(c,i){function h(j){h.superclass.constructor.call(this);a.Defer(this);this.config=j;var b=j.node;c.isPlainObject(b)||(b=d.get(j.node));this.node=this.el=b;this._backupProps={};this._propsData={}}var d=i("dom"),g=i("./base/utils"),f=i("./base/queue"),a=i("promise"),e=d.NodeType,b=c.noop,l={toggle:1,hide:1,show:1};c.extend(h,a,{on:function(a,c){"complete"===a?this.then(c):"end"===a?this.fin(c):"step"===a&&this.progress(c);
return this},prepareFx:b,runInternal:function(){var a=this,b=a.config,f=a.node,h,i=a._backupProps,o=a._propsData,k=b.to,r=b.delay||0,p=b.duration;g.saveRunningAnim(a);c.each(k,function(a,d){c.isPlainObject(a)||(a={value:a});o[d]=c.mix({delay:r,easing:b.easing,frame:b.frame,duration:p},a)});if(f.nodeType===e.ELEMENT_NODE){if(k.width||k.height)k=f.style,c.mix(i,{overflow:k.overflow,"overflow-x":k.overflowX,"overflow-y":k.overflowY}),k.overflow="hidden","inline"===d.css(f,"display")&&"none"===d.css(f,
"float")&&(10>c.UA.ieMode?k.zoom=1:k.display="inline-block");var q,n;n="none"===d.css(f,"display");c.each(o,function(c,b){h=c.value;if(l[h]){if("hide"===h&&n||"show"===h&&!n)return a.stop(!0),q=!1;i[b]=d.style(f,b);"toggle"===h&&(h=n?"show":"hide");"hide"===h?(c.value=0,i.display="none"):(c.value=d.css(f,b),d.css(f,b,0),d.show(f))}});if(!1===q)return}a.startTime=c.now();c.isEmptyObject(o)?(a.__totalTime=1E3*p,a.__waitTimeout=setTimeout(function(){a.stop(!0)},a.__totalTime)):(a.prepareFx(),a.doStart())},
isRunning:function(){return g.isAnimRunning(this)},isPaused:function(){return g.isAnimPaused(this)},pause:function(){this.isRunning()&&(this._runTime=c.now()-this.startTime,this.__totalTime-=this._runTime,g.removeRunningAnim(this),g.savePausedAnim(this),this.__waitTimeout?clearTimeout(this.__waitTimeout):this.doStop());return this},doStop:b,doStart:b,resume:function(){var a=this;a.isPaused()&&(a.startTime=c.now()-a._runTime,g.removePausedAnim(a),g.saveRunningAnim(a),a.__waitTimeout?a.__waitTimeout=
setTimeout(function(){a.stop(!0)},a.__totalTime):(a.beforeResume(),a.doStart()));return a},beforeResume:b,run:function(){var a;a=this.config.queue;!1===a?this.runInternal():(a=f.queue(this.node,a,this),1===a.length&&this.runInternal());return this},stop:function(a){var b=this.node,e=this.config.queue;if(this.isResolved()||this.isRejected())return this;this.__waitTimeout&&(clearTimeout(this.__waitTimeout),this.__waitTimeout=0);if(!this.isRunning()&&!this.isPaused())return!1!==e&&f.remove(b,e,this),
this;this.doStop(a);g.removeRunningAnim(this);g.removePausedAnim(this);var h=this.defer;if(a){var i,a=this.config.complete;c.isEmptyObject(i=this._backupProps)||d.css(this.node,i);a&&a.call(this);h.resolve([this])}else h.reject([this]);!1!==e&&(b=f.dequeue(b,e))&&b[0]&&b[0].runInternal();return this}});h.Utils=g;h.Q=f;return h});
/*
Copyright 2014, KISSY v1.49.10
MIT Licensed
build time: Dec 10 14:46
*/
KISSY.add("anim/timer/easing",[],function(){function j(a){return a}function e(a,b,n,f){var d=3*a-3*n+1,c=3*n-6*a,h=3*a,l=3*b-3*f+1,i=3*f-6*b,j=3*b;return function(a){a:{for(var b=a,f,n,k=0;8>k;k++){n=((d*b+c)*b+h)*b-a;if(m(n)<o){a=b;break a}f=(3*d*b+2*c)*b+h;if(m(f)<o)break;b-=n/f}f=1;k=0;for(b=a;f>k;){n=((d*b+c)*b+h)*b-a;if(m(n)<o)break;0<n?f=b:k=b;b=(f+k)/2}a=b}return((l*a+i)*a+j)*a}}var g=Math.PI,h=Math.pow,b=Math.sin,c=parseFloat,l=/^cubic-bezier\(([^,]+),([^,]+),([^,]+),([^,]+)\)$/i,i={swing:function(a){return-Math.cos(a*
g)/2+0.5},easeNone:j,linear:j,easeIn:function(a){return a*a},ease:e(0.25,0.1,0.25,1),"ease-in":e(0.42,0,1,1),"ease-out":e(0,0,0.58,1),"ease-in-out":e(0.42,0,0.58,1),"ease-out-in":e(0,0.42,1,0.58),toFn:function(a){var b;return(b=a.match(l))?e(c(b[1]),c(b[2]),c(b[3]),c(b[4])):i[a]||j},easeOut:function(a){return(2-a)*a},easeBoth:function(a){return 1>(a*=2)?0.5*a*a:0.5*(1- --a*(a-2))},easeInStrong:function(a){return a*a*a*a},easeOutStrong:function(a){return 1- --a*a*a*a},easeBothStrong:function(a){return 1>
(a*=2)?0.5*a*a*a*a:0.5*(2-(a-=2)*a*a*a)},elasticIn:function(a){return 0===a||1===a?a:-(h(2,10*(a-=1))*b(2*(a-0.075)*g/0.3))},elasticOut:function(a){return 0===a||1===a?a:h(2,-10*a)*b(2*(a-0.075)*g/0.3)+1},elasticBoth:function(a){return 0===a||2===(a*=2)?a:1>a?-0.5*h(2,10*(a-=1))*b(2*(a-0.1125)*g/0.45):0.5*h(2,-10*(a-=1))*b(2*(a-0.1125)*g/0.45)+1},backIn:function(a){1===a&&(a-=0.001);return a*a*(2.70158*a-1.70158)},backOut:function(a){return(a-=1)*a*(2.70158*a+1.70158)+1},backBoth:function(a){var b,
n=(b=2.5949095)+1;return 1>(a*=2)?0.5*a*a*(n*a-b):0.5*((a-=2)*a*(n*a+b)+2)},bounceIn:function(a){return 1-i.bounceOut(1-a)},bounceOut:function(a){return a<1/2.75?7.5625*a*a:a<2/2.75?7.5625*(a-=1.5/2.75)*a+0.75:a<2.5/2.75?7.5625*(a-=2.25/2.75)*a+0.9375:7.5625*(a-=2.625/2.75)*a+0.984375},bounceBoth:function(a){return 0.5>a?0.5*i.bounceIn(2*a):0.5*i.bounceOut(2*a-1)+0.5}},o=1.0E-6,m=Math.abs;return i});
KISSY.add("anim/timer/manager",[],function(j){var e=j.stamp,g,h;g=function(b){return setTimeout(b,15)};h=function(b){clearTimeout(b)};return{runnings:{},timer:null,start:function(b){var c=e(b);this.runnings[c]||(this.runnings[c]=b,this.startTimer())},stop:function(b){this.notRun(b)},notRun:function(b){delete this.runnings[e(b)];j.isEmptyObject(this.runnings)&&this.stopTimer()},pause:function(b){this.notRun(b)},resume:function(b){this.start(b)},startTimer:function(){var b=this;b.timer||(b.timer=g(function l(){b.runFrames()?
b.stopTimer():b.timer=g(l)}))},stopTimer:function(){var b=this.timer;b&&(h(b),this.timer=0)},runFrames:function(){var b,c,h=this.runnings;for(b in h)h[b].frame();for(b in h){c=0;break}return void 0===c}}});
KISSY.add("anim/timer/fx",["dom"],function(j,e){function g(b){j.mix(this,b);this.pos=0;this.unit=this.unit||""}var h=e("dom");g.prototype={isCustomFx:0,constructor:g,load:function(b){j.mix(this,b);this.pos=0;this.unit=this.unit||""},frame:function(b){if(1!==this.pos){var c=this.anim,g=this.prop,i=c.node,e=this.from,m=this.propData,a=this.to;if(void 0===b)var k=j.now(),b=m.duration,k=k-c.startTime-m.delay,b=0>=k?0:k>=b?1:m.easing(k/b);this.pos=b;e===a||0===b||(this.val=e=this.interpolate(e,a,this.pos),
m.frame?m.frame.call(this,c,this):this.isCustomFx||(void 0===e?(this.pos=1,e=a):e+=this.unit,this.val=e,"attr"===this.type?h.attr(i,g,e,1):h.css(i,g,e)))}},interpolate:function(b,c,h){if("number"===typeof b&&"number"===typeof c)return Math.round(1E5*(b+(c-b)*h))/1E5},cur:function(){var b=this.prop,c,e,g=this.anim.node;if(this.isCustomFx)return g[b]||0;if(!(c=this.type))c=this.type=(!g.style||null==g.style[b])&&null!=h.attr(g,b,void 0,1)?"attr":"css";b="attr"===c?h.attr(g,b,void 0,1):h.css(g,b);return isNaN(e=
parseFloat(b))?!b||"auto"===b?0:b:e}};g.Factories={};g.FxTypes={};g.getFx=function(b){var c=g,h,e;if(h=b.fxType)c=g.FxTypes[h];else if(!b.isCustomFx&&(e=g.Factories[b.prop]))c=e;return new c(b)};return g});
KISSY.add("anim/timer/short-hand",[],function(){return{background:[],border:["borderBottomWidth","borderLeftWidth","borderRightWidth","borderTopWidth"],borderBottom:["borderBottomWidth"],borderLeft:["borderLeftWidth"],borderTop:["borderTopWidth"],borderRight:["borderRightWidth"],font:["fontSize","fontWeight"],margin:["marginBottom","marginLeft","marginRight","marginTop"],padding:["paddingBottom","paddingLeft","paddingRight","paddingTop"]}});
KISSY.add("anim/timer/color",["./fx","./short-hand"],function(j,e){function g(b){var b=b+"",f;if(f=b.match(m))return[parseInt(f[1]),parseInt(f[2]),parseInt(f[3])];if(f=b.match(a))return[parseInt(f[1]),parseInt(f[2]),parseInt(f[3]),parseInt(f[4])];if(f=b.match(k)){for(b=1;b<f.length;b++)2>f[b].length&&(f[b]+=f[b]);return[parseInt(f[1],l),parseInt(f[2],l),parseInt(f[3],l)]}return o[b=b.toLowerCase()]?o[b]:[255,255,255]}function h(){h.superclass.constructor.apply(this,arguments)}var b=e("./fx"),c=e("./short-hand"),
l=16,i=Math.floor,o={black:[0,0,0],silver:[192,192,192],gray:[128,128,128],white:[255,255,255],maroon:[128,0,0],red:[255,0,0],purple:[128,0,128],fuchsia:[255,0,255],green:[0,128,0],lime:[0,255,0],olive:[128,128,0],yellow:[255,255,0],navy:[0,0,128],blue:[0,0,255],teal:[0,128,128],aqua:[0,255,255]},m=/^rgb\(([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\)$/i,a=/^rgba\(([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+),\s*([0-9]+)\)$/i,k=/^#?([0-9A-F]{1,2})([0-9A-F]{1,2})([0-9A-F]{1,2})$/i;c.background.push("backgroundColor");
c.borderColor=["borderBottomColor","borderLeftColor","borderRightColor","borderTopColor"];c.border.push("borderBottomColor","borderLeftColor","borderRightColor","borderTopColor");c.borderBottom.push("borderBottomColor");c.borderLeft.push("borderLeftColor");c.borderRight.push("borderRightColor");c.borderTop.push("borderTopColor");j.extend(h,b,{load:function(){h.superclass.load.apply(this,arguments);this.from&&(this.from=g(this.from));this.to&&(this.to=g(this.to))},interpolate:function(a,b,d){var k=
h.superclass.interpolate;if(3===a.length&&3===b.length)return"rgb("+[i(k(a[0],b[0],d)),i(k(a[1],b[1],d)),i(k(a[2],b[2],d))].join(", ")+")";if(4===a.length||4===b.length)return"rgba("+[i(k(a[0],b[0],d)),i(k(a[1],b[1],d)),i(k(a[2],b[2],d)),i(k(a[3]||1,b[3]||1,d))].join(", ")+")"}});j.each("backgroundColor,borderBottomColor,borderLeftColor,borderRightColor,borderTopColor,color,outlineColor".split(","),function(a){b.Factories[a]=h});return b.FxTypes.color=h});
KISSY.add("anim/timer/transform",["dom","./fx"],function(j,e){function g(a){a=a.split(/,/);return a=j.map(a,function(a){return b(a)})}function h(){return{translateX:0,translateY:0,rotate:0,skewX:0,skewY:0,scaleX:1,scaleY:1}}function b(a){return Math.round(1E5*parseFloat(a))/1E5}function c(a){for(var a=a.split(")"),k=j.trim,n=-1,f=a.length-1,d,e,c=h();++n<f;)switch(d=a[n].split("("),e=k(d[0]),d=d[1],e){case "translateX":case "translateY":case "scaleX":case "scaleY":c[e]=b(d);break;case "rotate":case "skewX":case "skewY":var i=
b(d);j.endsWith(d,"deg")||(i=180*i/Math.PI);c[e]=i;break;case "translate":case "translate3d":d=d.split(",");c.translateX=b(d[0]);c.translateY=b(d[1]||0);break;case "scale":d=d.split(",");c.scaleX=b(d[0]);c.scaleY=b(d[1]||d[0]);break;case "matrix":return a=d,a=g(a),f=n=k=void 0,e=a[0],c=a[1],d=a[2],i=a[3],e*i-c*d?(k=Math.sqrt(e*e+c*c),f=(e*d+c*i)/(e*i-d*c),n=(e*i-c*d)/k,e*i<c*d&&(f=-f,k=-k)):k=n=f=0,{translateX:b(a[4]),translateY:b(a[5]),rotate:b(180*Math.atan2(c,e)/Math.PI),skewX:b(180*Math.atan(f)/
Math.PI),skewY:0,scaleX:b(k),scaleY:b(n)}}return c}function l(){l.superclass.constructor.apply(this,arguments)}var i=e("dom"),o=e("./fx"),m=j.Features.isTransform3dSupported()?"translate3d({translateX}px,{translateY}px,0)":"translate({translateX}px,{translateY}px)";j.extend(l,o,{load:function(){l.superclass.load.apply(this,arguments);this.from=(this.from=i.style(this.anim.node,"transform")||this.from)&&"none"!==this.from?c(this.from):h();this.to=this.to?c(this.to):h()},interpolate:function(a,b,c){var f=
l.superclass.interpolate,d={};d.translateX=f(a.translateX,b.translateX,c);d.translateY=f(a.translateY,b.translateY,c);d.rotate=f(a.rotate,b.rotate,c);d.skewX=f(a.skewX,b.skewX,c);d.skewY=f(a.skewY,b.skewY,c);d.scaleX=f(a.scaleX,b.scaleX,c);d.scaleY=f(a.scaleY,b.scaleY,c);return j.substitute(m+" rotate({rotate}deg) skewX({skewX}deg) skewY({skewY}deg) scale({scaleX},{scaleY})",d)}});return o.Factories.transform=l});
KISSY.add("anim/timer","dom,./base,./timer/easing,./timer/manager,./timer/fx,./timer/short-hand,./timer/color,./timer/transform".split(","),function(j,e){function g(){var a;g.superclass.constructor.apply(this,arguments);j.each(a=this.to,function(b,c){var d=m(c);if(c!==d){a[d]=a[c];delete a[c]}})}var h=e("dom"),b=e("./base"),c=e("./timer/easing"),l=e("./timer/manager"),i=e("./timer/fx"),o=e("./timer/short-hand");e("./timer/color");e("./timer/transform");var m=h._camelCase,a=/^([+\-]=)?([\d+.\-]+)([a-z%]*)$/i;
j.extend(g,b,{prepareFx:function(){var b=this.node,e=this._propsData;j.each(e,function(a){a.duration=a.duration*1E3;a.delay=a.delay*1E3;if(typeof a.easing==="string")a.easing=c.toFn(a.easing)});j.each(o,function(a,c){var d,f=e[c],g;if(f){g=f.value;d={};j.each(a,function(a){d[a]=h.css(b,a)});h.css(b,c,g);j.each(d,function(a,c){c in e||(e[c]=j.merge(f,{value:h.css(b,c)}));h.css(b,c,a)});delete e[c]}});var f,d,g,l,m,p,r,u=0,q;j.isPlainObject(b)&&(u=1);for(f in e){d=e[f];g=d.value;p={isCustomFx:u,prop:f,
anim:this,fxType:d.fxType,type:d.type,propData:d};r=i.getFx(p);l=g;m=r.cur();g=g+"";q="";if(g=g.match(a)){l=parseFloat(g[2]);if((q=g[3])&&q!=="px"&&m){var s=0,t=l;do{++t;h.css(b,f,t+q);s=r.cur()}while(s===0);m=t/s*m;h.css(b,f,m+q)}g[1]&&(l=(g[1]==="-="?-1:1)*l+m)}p.from=m;p.to=l;p.unit=q;r.load(p);d.fx=r}},frame:function(){var a,b=1,c,d=this._propsData;for(a in d){c=d[a];c=c.fx;c.frame();if(this.isRejected()||this.isResolved())return;b=b&c.pos===1}d=j.now();a=this.config.duration*1E3;d=Math.max(0,
this.startTime+a-d);this.defer.notify([this,1-(d/a||0),d]);b&&this.stop(b)},doStop:function(a){var b,c=this._propsData;l.stop(this);if(a)for(b in c){a=c[b];(a=a.fx)&&a.frame(1)}},doStart:function(){l.start(this)}});g.Easing=c;g.Fx=i;return g});
/*
Copyright 2014, KISSY v1.49.10
MIT Licensed
build time: Dec 10 14:46
*/
KISSY.add("anim/transition",["dom","./base"],function(k,n,x,q){function r(a,c){return c.toUpperCase()}function o(a){-1!==a.indexOf("-")&&(a=a.replace(s,r));if(a in g)return g[a];if(!m||a in m)g[a]={propertyName:a,propertyNamePrefix:""};else{for(var c=a.charAt(0).toUpperCase()+a.slice(1),d,b=0;b<t;b++){var e=p[b];d=e+c;d in m&&(g[a]={propertyName:d,propertyNamePrefix:e})}g[a]=g[a]||null}return g[a]}function u(a){var c="";h.each(a,function(a,b){c&&(c+=",");c+=b+" "+a.duration+"s "+a.easing+" "+a.delay+
"s"});return c}function v(a){return a.replace(/[A-Z]/g,function(a){return"-"+a.toLowerCase()})}function i(a,c,d,b,e){if(!(this instanceof i))return new i(a,c,d,b,e);i.superclass.constructor.apply(this,arguments)}var s=/-([a-z])/ig,p=["Webkit","Moz","O","ms"],t=p.length,g={},m=document.documentElement.style,h=k,j=n("dom"),k=n("./base"),l=o("transition").propertyName,w={ease:1,linear:1,"ease-in":1,"ease-out":1,"ease-in-out":1};h.extend(i,k,{prepareFx:function(){var a=this._propsData,c={},d,b;for(b in a)d=
a[b],"string"===typeof d.easing?!h.startsWith(d.easing,"cubic-bezier")&&!w[d.easing]&&(d.easing="linear"):d.easing="linear",(d=o(b))&&(c[v(d.propertyName)]=a[b]);this._propsData=c},doStart:function(){var a=this,c=a.node,d=c.style,b=a._propsData,e=d[l],f=0,g={};h.each(b,function(a,b){var d=a.value;j.css(c,b,j.css(c,b));g[b]=d;f=Math.max(a.duration+a.delay,f)});-1!==e.indexOf("none")?e="":e&&(e+=",");d[l]=e+u(b);setTimeout(function(){j.css(c,g)},0);a._transitionEndTimer=setTimeout(function(){a.stop(!0)},
1E3*f)},beforeResume:function(){var a=this._propsData,c=h.merge(a),d=this._runTime/1E3;h.each(c,function(b,c){var f=d;b.delay>=f?b.delay-=f:(f-=b.delay,b.delay=0,b.duration>=f?b.duration-=f:delete a[c])})},doStop:function(a){var c=this.node,d=c.style,b=this._propsData,e=[],f={};this._transitionEndTimer&&(clearTimeout(this._transitionEndTimer),this._transitionEndTimer=null);h.each(b,function(b,d){a||(f[d]=j.css(c,d));e.push(d)});b=h.trim(d[l].replace(RegExp("(^|,)\\s*(?:"+e.join("|")+")\\s+[^,]+",
"gi"),"$1")).replace(/^,|,,|,$/g,"")||"none";d[l]=b;j.css(c,f)}});h.mix(i,k.Statics);q.exports=i});
/*
Copyright 2014, KISSY v1.49.10
MIT Licensed
build time: Dec 10 14:47
*/
KISSY.add("combobox/combobox-xtpl",[],function(){return function(f){var a,d=this;a=this.config.utils;var j=a.runBlockCommand,k=a.renderOutput,g=a.getProperty,h=a.runInlineCommand,e=a.getPropertyOrRunCommand;a='<div id="ks-combobox-invalid-el-';var c=e(d,f,{},"id",0,1);a+=k(c,!0);a+='"\n     class="';var c={},b=[];b.push("invalid-el");c.params=b;c=h(d,f,c,"getBaseCssClasses",2);a+=k(c,!0);a+='">\n    <div class="';c={};b=[];b.push("invalid-inner");c.params=b;c=h(d,f,c,"getBaseCssClasses",3);a+=k(c,
!0);a+='"></div>\n</div>\n\n';var c={},b=[],m=g(d,f,"hasTrigger",0,6);b.push(m);c.params=b;c.fn=function(c){var a;a='\n<div id="ks-combobox-trigger-';var b=e(d,c,{},"id",0,7);a+=k(b,!0);a+='"\n     class="';var b={},g=[];g.push("trigger");b.params=g;b=h(d,c,b,"getBaseCssClasses",8);a+=k(b,!0);a+='">\n    <div class="';b={};g=[];g.push("trigger-inner");b.params=g;c=h(d,c,b,"getBaseCssClasses",9);a+=k(c,!0);return a+'">&#x25BC;</div>\n</div>\n'};a+=j(d,f,c,"if",6);a+='\n\n<div class="';c={};b=[];b.push("input-wrap");
c.params=b;c=h(d,f,c,"getBaseCssClasses",13);a+=k(c,!0);a+='">\n\n    <input id="ks-combobox-input-';c=e(d,f,{},"id",0,15);a+=k(c,!0);a+='"\n           aria-haspopup="true"\n           aria-autocomplete="list"\n           aria-haspopup="true"\n           role="autocomplete"\n           aria-expanded="false"\n\n    ';c={};b=[];m=g(d,f,"disabled",0,22);b.push(m);c.params=b;c.fn=function(){return"\n    disabled\n    "};a+=j(d,f,c,"if",22);a+='\n\n    autocomplete="off"\n    class="';c={};b=[];b.push("input");
c.params=b;c=h(d,f,c,"getBaseCssClasses",27);a+=k(c,!0);a+='"\n\n    value="';c=e(d,f,{},"value",0,29);a+=k(c,!0);a+='"\n    />\n\n\n    <label id="ks-combobox-placeholder-';c=e(d,f,{},"id",0,33);a+=k(c,!0);a+='"\n           for="ks-combobox-input-';c=e(d,f,{},"id",0,34);a+=k(c,!0);a+="\"\n            style='display:";c={};b=[];g=g(d,f,"value",0,35);b.push(g);c.params=b;c.fn=function(){return"none"};c.inverse=function(){return"block"};a+=j(d,f,c,"if",35);a+=";'\n    class=\"";j={};g=[];g.push("placeholder");
j.params=g;j=h(d,f,j,"getBaseCssClasses",36);a+=k(j,!0);a+='">\n    ';f=e(d,f,{},"placeholder",0,37);a+=k(f,!0);return a+"\n    </label>\n</div>\n"}});
KISSY.add("combobox/render",["component/control","./combobox-xtpl"],function(f,a){var d=a("component/control"),j=a("./combobox-xtpl");return d.getDefaultRender().extend({beforeCreateDom:function(a,d){f.mix(d,{input:"#ks-combobox-input-{id}",trigger:"#ks-combobox-trigger-{id}",invalidEl:"#ks-combobox-invalid-el-{id}",placeholderEl:"#ks-combobox-placeholder-{id}"})},getKeyEventTarget:function(){return this.control.get("input")},_onSetCollapsed:function(a){this.control.get("input").attr("aria-expanded",
!a)},_onSetDisabled:function(a,d){this.callSuper(a,d);this.control.get("input").attr("disabled",a)}},{ATTRS:{contentTpl:{value:j}},HTML_PARSER:{value:function(a){return a.one("."+this.getBaseCssClass("input")).val()},input:function(a){return a.one("."+this.getBaseCssClass("input"))},trigger:function(a){return a.one("."+this.getBaseCssClass("trigger"))},invalidEl:function(a){return a.one("."+this.getBaseCssClass("invalid-el"))},placeholderEl:function(a){return a.one("."+this.getBaseCssClass("placeholder"))}}})});
KISSY.add("combobox/control",["node","component/control","./render","menu"],function(f,a){function d(a){for(var c=0;c<a.length;c++)if(!a[c].get("disabled"))return a[c];return null}function j(){b(this)}function k(){var a=this;setTimeout(function(){m(a)},0)}function g(){this.focus();m(this)}function h(){this.setValueFromAutocomplete(this.getValueForAutocomplete(),{force:1})}function e(a){a=a.target;a.isMenuItem&&(a=a.get("textContent"),this.setValueFromAutocomplete(a),this._savedValue=a,this.set("collapsed",
!0))}function c(a,c){var b=a.$el,e=a.view.getBaseCssClasses("invalid"),d=a.get("invalidEl");c?(b.addClass(e),d.attr("title",c),d.show()):(b.removeClass(e),d.hide())}function b(a){a._focusoutDismissTimer||(a._focusoutDismissTimer=setTimeout(function(){a._focusoutDismissTimer&&a.set("collapsed",!0)},50))}function m(a){var c=a._focusoutDismissTimer;c&&(clearTimeout(c),a._focusoutDismissTimer=null)}function s(a){this.set("value",a.newVal,{data:{causedByTimer:1}})}function i(a){var c,b=[],e,d,b=this.get("menu"),
a=this.normalizeData(a);b.set("highlightedItem",null);b.removeChildren(!0);(d=b.get("highlightedItem"))&&d.set("highlighted",!1);if(a&&a.length){for(d=0;d<a.length;d++)c=a[d],b.addChild(c);b=b.get("children");a=this.getValueForAutocomplete();if(this.get("highlightMatchItem"))for(d=0;d<b.length;d++)if(b[d].get("textContent")===a){b[d].set("highlighted",!0);e=!0;break}if(!e&&this.get("autoHighlightFirst"))for(d=0;d<b.length;d++)if(!b[d].get("disabled")){b[d].set("highlighted",!0);break}this.set("collapsed",
!1);this.fire("afterRenderData")}else this.set("collapsed",!0)}var t=a("node"),p=a("component/control"),o=a("./render");a("menu");var l=t.KeyCode;return p.extend([],{initializer:function(){this.publish("afterRenderData",{bubbles:!1})},_savedValue:null,normalizeData:function(a){var c,b,d;if(a&&a.length){a=a.slice(0,this.get("maxItemCount"));c=this.get("format")?this.get("format").call(this,this.getValueForAutocomplete(),a):[];for(d=0;d<a.length;d++)b=a[d],c[d]=f.mix({content:b,textContent:b,value:b},
c[d])}return c},bindUI:function(){var a=this;a.get("input").on("valuechange",s,a);a.on("click",e,a);a.get("menu").onRendered(function(c){var b=a.get("input"),d=c.get("el"),c=c.get("contentEl");b.attr("aria-owns",d.attr("id"));d.on("focusout",j,a);d.on("focusin",k,a);c.on("mouseover",g,a);c.on("mousedown",h,a)})},destructor:function(){this.get("menu").destroy()},getValueForAutocomplete:function(){return this.get("value")},setValueFromAutocomplete:function(a,c){this.set("value",a,c)},_onSetValue:function(a,
c){var b;c.causedByTimer?(b=this.getValueForAutocomplete(),void 0===b?this.set("collapsed",!0):(this._savedValue=b,this.sendRequest(b))):this.get("input").val(a)},handleFocusInternal:function(){var a;m(this);this.get("invalidEl")&&c(this,!1);(a=this.get("placeholderEl"))&&a.hide()},handleBlurInternal:function(a){var d=this,e=d.get("placeholderEl");d.callSuper(a);b(d);d.get("invalidEl")&&d.validate(function(a,b){a?!d.get("focused")&&b===d.get("value")&&c(d,a):c(d,!1)});e&&!d.get("value")&&e.show()},
handleMouseDownInternal:function(a){var c,b;this.callSuper(a);c=a.target;if((b=this.get("trigger"))&&(b[0]===c||b.contains(c)))this.get("collapsed")?(this.focus(),this.sendRequest("")):this.set("collapsed",!0),a.preventDefault()},handleKeyDownInternal:function(a){var c,b=a.keyCode,e,g,h=this.get("menu");this.get("input");c=this.get("updateInputOnDownUp");if(h.get("visible")){e=h.get("highlightedItem");if(c&&e&&(g=h.get("children"),b===l.DOWN&&e===d(g.concat().reverse())||b===l.UP&&e===d(g)))return this.setValueFromAutocomplete(this._savedValue),
e.set("highlighted",!1),!0;g=h.handleKeyDownInternal(a);e=h.get("highlightedItem");if(b===l.ESC)return this.set("collapsed",!0),c&&this.setValueFromAutocomplete(this._savedValue),!0;c&&f.inArray(b,[l.DOWN,l.UP])&&this.setValueFromAutocomplete(e.get("textContent"));return b===l.TAB&&e&&(e.handleClickInternal(a),this.get("multiple"))?!0:g}if(b===l.DOWN||b===l.UP)if(a=this.getValueForAutocomplete(),void 0!==a)return this.sendRequest(a),!0},validate:function(a){var c=this.get("validator"),b=this.getValueForAutocomplete();
c?c(b,function(c){a(c,b)}):a(!1,b)},sendRequest:function(a){this.get("dataSource").fetchData(a,i,this)},_onSetCollapsed:function(a){var c=this.$el,b=this.get("menu");a?b.hide():(m(this),b.get("visible")||(this.get("matchElWidth")&&(b.render(),a=b.get("el"),a=(parseInt(a.css("borderLeftWidth"))||0)+(parseInt(a.css("borderRightWidth"))||0),b.set("width",c[0].offsetWidth-a)),b.show()))}},{ATTRS:{input:{},value:{value:"",sync:0,view:1},trigger:{},placeholder:{view:1},placeholderEl:{},validator:{},invalidEl:{},
allowTextSelection:{value:!0},hasTrigger:{value:!0,view:1},menu:{value:{},getter:function(a){a.isControl||(a.xclass=a.xclass||"popupmenu",a=this.createComponent(a),this.setInternal("menu",a));return a},setter:function(a){if(a.isControl){a.setInternal("parent",this);var c={node:this.$el,points:["bl","tl"],overflow:{adjustX:1,adjustY:1}};f.mix(a.get("align"),c,!1)}}},collapsed:{view:1,value:!0},dataSource:{},maxItemCount:{value:99999},matchElWidth:{value:!0},format:{},updateInputOnDownUp:{value:!0},
autoHighlightFirst:{},highlightMatchItem:{value:!0},xrender:{value:o}},xclass:"combobox"})});
KISSY.add("combobox/cursor",["node"],function(f,a){function d(a){var c=g;c||(c=j(k));"textarea"===""+a[0].type.toLowerCase()?c.css("width",a.css("width")):c.css("width",9999);f.each(h,function(b){c.css(b,a.css(b))});g||c.insertBefore(a[0].ownerDocument.body.firstChild);return g=c}var j=a("node").all,k='<div style="z-index:-9999;overflow:hidden;position: fixed;left:-9999px;top:-9999px;opacity:0;white-space:pre-wrap;word-wrap:break-word;"></div>',g,h="paddingLeft,paddingTop,paddingBottom,paddingRight,marginLeft,marginTop,marginBottom,marginRight,borderLeftStyle,borderTopStyle,borderBottomStyle,borderRightStyle,borderLeftWidth,borderTopWidth,borderBottomWidth,borderRightWidth,line-height,outline,height,fontFamily,fontSize,fontWeight,fontVariant,fontStyle".split(",");
return function(a){var c=j(a),a=c[0],b=a.ownerDocument,g=j(b),h=a.scrollTop,i=a.scrollLeft;if(b.selection)return a=b.selection.createRange(),{left:a.boundingLeft+i+g.scrollLeft(),top:a.boundingTop+h+a.boundingHeight+g.scrollTop()};g=c.offset();if("textarea"!==a.type)return g.top+=a.offsetHeight,g;b=d(c);c=a.selectionStart;b.html(f.escapeHtml(a.value.substring(0,c-1))+"<span>x</span>");b.offset(g);g=b.last();a=g.offset();a.top+=g.height();0<c&&(a.left+=g.width());a.top-=h;a.left-=i;return a}});
KISSY.add("combobox/multi-value-combobox",["./cursor","./control"],function(f,a){function d(a,b){return b&&-1!==a.indexOf(b)}function j(a){a.newVal&&a.target===this.get("menu")&&this.alignWithCursor()}function k(a){var b=a.get("input"),e=a.get("value"),f=[],i=[],k=a.get("literal"),j=a.get("separator"),a=a.get("separatorType"),o=!1,l=a!==g,b=b.prop("selectionStart"),q,n,r=-1;for(q=0;q<e.length;q++)(n=e.charAt(q),k&&n===k&&(o=!o),o)?i.push(n):(q===b&&(r=f.length),l&&h.test(n))?(i.length&&f.push(i.join("")),
i=[],i.push(n)):d(j,n)?a===g?(i.push(n),i.length&&f.push(i.join("")),i=[]):(i.length&&f.push(i.join("")),i=[],i.push(n)):i.push(n);i.length&&f.push(i.join(""));f.length||f.push("");-1===r&&(a===g&&d(j,n)&&f.push(""),r=f.length-1);return{tokens:f,cursorPosition:b,tokenIndex:r}}var g="suffix",h=/\s|\xa0/,e=a("./cursor");return a("./control").extend({syncUI:function(){var a;this.get("alignWithCursor")&&(a=this.get("menu"),a.setInternal("align",null),a.on("beforeVisibleChange",j,this))},getValueForAutocomplete:function(){var a=
k(this),b=a.tokens,h=a.tokenIndex,a=this.get("separator"),f=this.get("separatorType"),b=b[h],h=b.length-1;if(f!==g)if(d(a,b.charAt(0)))b=b.slice(1);else return;else f===g&&d(a,b.charAt(h))&&(b=b.slice(0,h));return b},setValueFromAutocomplete:function(a,b){var f=this.get("input"),e=k(this),i=e.tokens,e=Math.max(0,e.tokenIndex),j=this.get("separator"),p;p=this.get("separatorType");var o=i[e+1]||"",l=i[e];if(p!==g){if(i[e]=l.charAt(0)+a,a&&(!o||!h.test(o.charAt(0))))i[e]+=" "}else i[e]=a,p=l.length-
1,d(j,l.charAt(p))?i[e]+=l.charAt(p):1===j.length&&(i[e]+=j);e=i.slice(0,e+1).join("").length;this.set("value",i.join(""),b);f.prop("selectionStart",e);f.prop("selectionEnd",e)},alignWithCursor:function(){var a=this.get("menu"),b;b=this.get("input");b=e(b);a.move(b.left,b.top)}},{ATTRS:{separator:{value:",;"},separatorType:{value:g},literal:{value:'"'},alignWithCursor:{}},xclass:"multi-value-combobox"})});
KISSY.add("combobox/filter-select",["./control"],function(f,a,d,j){f=a("./control");j.exports=f.extend({validate:function(a){var d=this;d.callSuper(function(h,e){h?a(h,e):d.get("dataSource").fetchData(e,function(c){a:{if(c=d.normalizeData(c))for(var b=0;b<c.length;b++)if(c[b].textContent===e){c=c[b];break a}c=!1}a(c?"":d.get("invalidMessage"),e,c)})})}},{ATTRS:{invalidMessage:{value:"invalid input"}}})});
KISSY.add("combobox/local-data-source",["attribute"],function(f,a){return a("attribute").extend({fetchData:function(a,f,k){var g=this.get("parse"),h=this.get("data"),h=g(a,h);f.call(k,h)}},{ATTRS:{data:{value:[]},parse:{value:function(a,j){var k=[],g=0;if(!a)return j;f.each(j,function(f){-1!==f.indexOf(a)&&k.push(f);g++});return k}}}})});
KISSY.add("combobox/remote-data-source",["io","attribute"],function(f,a){var d=a("io");return a("attribute").extend({fetchData:function(a,f,g){var h=this,e,c=h.get("paramName"),b=h.get("parse"),m=h.get("cache"),s=h.get("allowEmpty");h.caches=h.caches||{};h.io&&(h.io.abort(),h.io=null);if(!a&&!0!==s)return f.call(g,[]);if(m&&(e=h.caches[a]))return f.call(g,e);e=h.get("xhrCfg");e.data=e.data||{};e.data[c]=a;e.success=function(c){b&&(c=b(a,c));h.setInternal("data",c);m&&(h.caches[a]=c);f.call(g,c)};
h.io=d(e)}},{ATTRS:{paramName:{value:"q"},allowEmpty:{},cache:{},parse:{},xhrCfg:{value:{}}}})});
KISSY.add("combobox",["combobox/control","combobox/multi-value-combobox","combobox/filter-select","combobox/local-data-source","combobox/remote-data-source"],function(f,a){var d=a("combobox/control"),j=a("combobox/multi-value-combobox"),k=a("combobox/filter-select"),g=a("combobox/local-data-source"),h=a("combobox/remote-data-source");d.LocalDataSource=g;d.RemoteDataSource=h;d.FilterSelect=k;d.MultiValueComboBox=j;return d});
/*
Copyright 2014, KISSY v1.49.10
MIT Licensed
build time: Dec 10 14:47
*/
KISSY.add("component/control/process",["base","promise"],function(f,c){function h(d){d.fire("beforeSyncUI");d.syncUI();d.__callPluginsMethod("pluginSyncUI");d.fire("afterSyncUI")}var k=c("base"),m=c("promise").Defer,g=k.prototype.__getHook,e=f.noop,i=k.extend({bindInternal:e,syncInternal:e,initializer:function(){this._renderedDefer=new m},renderUI:e,syncUI:e,bindUI:e,onRendered:function(d){return this._renderedDefer.promise.then(d)},create:function(){this.get("created")||(this.fire("beforeCreateDom"),
this.createInternal(),this.__callPluginsMethod("pluginCreateDom"),this.fire("afterCreateDom"),this.setInternal("created",!0));return this},createInternal:function(){this.createDom()},render:function(){this.get("rendered")||(this.create(),this.fire("beforeRenderUI"),this.renderUI(),this.__callPluginsMethod("pluginRenderUI"),this.fire("afterRenderUI"),this.fire("beforeBindUI"),i.superclass.bindInternal.call(this),this.bindUI(),this.__callPluginsMethod("pluginBindUI"),this.fire("afterBindUI"),i.superclass.syncInternal.call(this),
h(this),this.setInternal("rendered",!0));return this},sync:function(){h(this)},plug:function(d){var c=this.get("plugins");this.callSuper(d);d=c[c.length-1];this.get("rendered")?(d.pluginCreateDom&&d.pluginCreateDom(this),d.pluginRenderUI&&d.pluginCreateDom(this),d.pluginBindUI&&d.pluginBindUI(this),d.pluginSyncUI&&d.pluginSyncUI(this)):this.get("created")&&d.pluginCreateDom&&d.pluginCreateDom(this);return this}},{__hooks__:{createDom:g("__createDom"),renderUI:g("__renderUI"),bindUI:g("__bindUI"),
syncUI:g("__syncUI")},name:"ComponentProcess",ATTRS:{rendered:{value:!1,setter:function(c){c&&this._renderedDefer.resolve(this)}},created:{value:!1}}});return i});
KISSY.add("component/control/render-xtpl",[],function(){return function(f){var c,h=this;c=this.config.utils;var k=c.runBlockCommand,m=c.renderOutput,g=c.getProperty,e=c.runInlineCommand,i=c.getPropertyOrRunCommand;c='<div id="';var d=i(h,f,{},"id",0,1);c+=m(d,!0);c+='"\n class="';var d={},n=[];n.push("");d.params=n;e=e(h,f,d,"getBaseCssClasses",2);c+=m(e,!0);c+="\n";e={};d=[];n=g(h,f,"elCls",0,3);d.push(n);e.params=d;e.fn=function(a){var b;b="\n ";a=i(h,a,{},".",0,4);b+=m(a,!0);return b+"  \n"};c+=
k(h,f,e,"each",3);c+='\n"\n\n';e={};d=[];n=g(h,f,"elAttrs",0,8);d.push(n);e.params=d;e.fn=function(a){var b;b=" \n ";var c=i(h,a,{},"xindex",0,9);b+=m(c,!0);b+='="';a=i(h,a,{},".",0,9);b+=m(a,!0);return b+'"\n'};c+=k(h,f,e,"each",8);c+='\n\nstyle="\n';e={};d=[];g=g(h,f,"elStyle",0,13);d.push(g);e.params=d;e.fn=function(a){var b;b=" \n ";var c=i(h,a,{},"xindex",0,14);b+=m(c,!0);b+=":";a=i(h,a,{},".",0,14);b+=m(a,!0);return b+";\n"};c+=k(h,f,e,"each",13);return c+'\n">'}});
KISSY.add("component/control/render",["node","xtemplate/runtime","./process","./render-xtpl","component/manager"],function(f,c){function h(j){"number"===typeof j&&(j+="px");return j}function k(j){j||(j=[""]);"string"===typeof j&&(j=j.split(/\s+/));return j}function m(j,a,b){for(var c="",d=0,f=b.length,a=j+a;d<f;d++)j=(j=b[d])?"-"+j:j,c+=" "+a+j;return c}function g(j){var a;j.target===this.control&&(a=this[o+j.type.slice(5).slice(0,-6)],a.call(this,j.newVal,j))}function e(a,l){return this.config.view.getBaseCssClasses(l.params[0])}
function i(a,l){return this.config.view.getBaseCssClass(l.params[0])}var d=c("node"),n=c("xtemplate/runtime"),a=c("./process"),b=c("./render-xtpl"),q=c("component/manager"),o="_onSet",p=f.trim,r=d.all,s=f.UA,t=f.Env.host.document;return a.extend({isRender:!0,createInternal:function(){var a=this.control.get("srcNode");a?this.decorateDom(a):this.callSuper()},beforeCreateDom:function(a){var l=this.control,b,c,d,f=l.get("elAttrs"),e=l.get("elCls"),g;b=l.getAttrs();g=l.get("elStyle");var m=l.get("elCls");
for(c in b)d=b[c],d.view&&(a[c]=l.get(c));b=a.width;c=a.height;d=a.visible;a=a.zIndex;b&&(g.width=h(b));c&&(g.height=h(c));a&&(g["z-index"]=a);d||m.push(this.getBaseCssClasses("hidden"));if(g=l.get("disabled"))e.push(this.getBaseCssClasses("disabled")),f["aria-disabled"]="true";l.get("highlighted")&&e.push(this.getBaseCssClasses("hover"));l.get("focusable")&&(9>s.ieMode&&(f.hideFocus="true"),f.tabindex=g?"-1":"0")},createDom:function(){this.beforeCreateDom(this.renderData={},this.childrenElSelectors=
{},this.renderCommands={getBaseCssClasses:e,getBaseCssClass:i});var a=this.control,l;l=this.renderTpl(b)+this.renderTpl(this.get("contentTpl"))+"</div>";a.setInternal("el",this.$el=r(l));this.el=this.$el[0];this.fillChildrenElsBySelectors()},decorateDom:function(a){var b=this.control;a.attr("id")||a.attr("id",b.get("id"));var c=this.constructor.HTML_PARSER,d,e;for(d in c)e=c[d],"function"===typeof e?(e=e.call(this,a),void 0!==e&&b.setInternal(d,e)):"string"===typeof e?b.setInternal(d,a.one(e)):f.isArray(e)&&
e[0]&&b.setInternal(d,a.all(e[0]));b.setInternal("el",this.$el=a);this.el=a[0]},renderUI:function(){var a=this.control,b=this.$el;if(!a.get("srcNode")){var c=a.get("render");(a=a.get("elBefore"))?b.insertBefore(a,void 0):c?b.appendTo(c,void 0):b.appendTo(t.body,void 0)}},bindUI:function(){var a=this.control,b=a.getAttrs(),c,d;for(c in b){d=b[c];var e=f.ucfirst(c),h=this[o+e];if(d.view&&h)a.on("after"+e+"Change",g,this)}},destructor:function(){this.$el&&this.$el.remove()},$:function(a){return this.$el.all(a)},
fillChildrenElsBySelectors:function(a){var b=this.$el,c=this.control,d,e,a=a||this.childrenElSelectors;for(d in a)e=a[d],"function"===typeof e?c.setInternal(d,e(b)):c.setInternal(d,this.$(f.substitute(e,this.renderData))),delete a[d]},renderTpl:function(a,b,c){b=b||this.renderData;c=c||this.renderCommands;return(new (this.get("xtemplate"))(a,{control:this.control,view:this,commands:c})).render(b)},getComponentConstructorByNode:function(a,b){var c=b[0].className;if(c){for(var c=c.split(/\s+/),d=[],
e=0,h=c.length;e<h;e++){var g=f.trim(c[e]);g&&f.startsWith(g,a)&&d.push(g.substring(a.length))}c=d.join(" ");return q.getConstructorByXClass(c)}return null},getComponentCssClasses:function(){if(this.componentCssClasses)return this.componentCssClasses;for(var a=this.control.constructor,b,c=[];a&&!a.prototype.hasOwnProperty("isControl");)(b=a.xclass)&&c.push(b),a=a.superclass&&a.superclass.constructor;return this.componentCssClasses=c},getBaseCssClasses:function(a){for(var a=k(a),b=this.getComponentCssClasses(),
c=0,d=this.get("control"),e="",f=b.length,d=d.get("prefixCls");c<f;c++)e+=m(d,b[c],a);return p(e)},getBaseCssClass:function(a){return p(m(this.control.get("prefixCls"),this.getComponentCssClasses()[0],k(a)))},getKeyEventTarget:function(){return this.$el},_onSetWidth:function(a){this.$el.width(a)},_onSetHeight:function(a){this.$el.height(a)},_onSetContent:function(a){var b=this.$el;b.html(a);this.get("allowTextSelection")||b.unselectable()},_onSetVisible:function(a){var b=this.$el,c=this.getBaseCssClasses("hidden");
a?b.removeClass(c):b.addClass(c)},_onSetHighlighted:function(a){var b=this.getBaseCssClasses("hover");this.$el[a?"addClass":"removeClass"](b)},_onSetDisabled:function(a){var b=this.control,c=this.getBaseCssClasses("disabled");this.$el[a?"addClass":"removeClass"](c).attr("aria-disabled",a);b.get("focusable")&&this.getKeyEventTarget().attr("tabindex",a?-1:0)},_onSetActive:function(a){var b=this.getBaseCssClasses("active");this.$el[a?"addClass":"removeClass"](b).attr("aria-pressed",!!a)},_onSetFocused:function(a){var b=
this.$el,c=this.getBaseCssClasses("focused");b[a?"addClass":"removeClass"](c)},_onSetZIndex:function(a){this.$el.css("z-index",a)}},{__hooks__:{decorateDom:a.prototype.__getHook("__decorateDom"),beforeCreateDom:a.prototype.__getHook("__beforeCreateDom")},extend:function l(b,c,d){var e,g={};e=a.extend.apply(this,arguments);e.HTML_PARSER=e.HTML_PARSER||{};f.isArray(b)&&(f.each(b.concat(e),function(a){a&&f.each(a.HTML_PARSER,function(a,b){g[b]=a})}),e.HTML_PARSER=g);f.mix(e.HTML_PARSER,this.HTML_PARSER,
!1);e.extend=l;return e},ATTRS:{control:{setter:function(a){this.control=a}},xtemplate:{value:n},contentTpl:{value:function(a){return a.get("content")||""}}},HTML_PARSER:{id:function(a){return(a=a[0].id)?a:void 0},content:function(a){return a.html()},disabled:function(a){return a.hasClass(this.getBaseCssClass("disabled"))}},name:"render"})});
KISSY.add("component/control",["node","./control/process","component/manager","./control/render"],function(f,c){function h(){var a,b=this;do a=b.ATTRS,b=b.superclass;while(!a||!a.xrender);return a.xrender.value}var k=c("node"),m=c("./control/process"),g=c("component/manager"),e=c("./control/render"),i=f.UA.ieMode,d=k.Gesture,n=f.Features.isTouchGestureSupported(),e=m.extend({isControl:!0,createDom:function(){var a=this.get("xrender"),b=this.get("view"),c=this.get("id");b?b.set("control",this):this.set("view",
this.view=b=new a({control:this}));b.create();a=b.getKeyEventTarget();this.get("allowTextSelection")||a.unselectable();g.addComponent(c,this)},renderUI:function(){this.view.render()},bindUI:function(){var a=this.view.getKeyEventTarget();if(this.get("focusable"))a.on("focus",this.handleFocus,this).on("blur",this.handleBlur,this).on("keydown",this.handleKeydown,this);if(this.get("handleMouseEvents")){a=this.$el;a.on("mouseenter",this.handleMouseEnter,this).on("mouseleave",this.handleMouseLeave,this).on("contextmenu",
this.handleContextMenu,this);a.on(d.start,this.handleMouseDown,this).on(d.end,this.handleMouseUp,this).on(d.tap,this.handleClick,this);if(d.cancel)a.on(d.cancel,this.handleMouseUp,this);if(9>i)a.on("dblclick",this.handleDblClick,this)}},sync:function(){this.fire("beforeSyncUI");this.syncUI();this.view.sync();this.__callPluginsMethod("pluginSyncUI");this.fire("afterSyncUI")},createComponent:function(a,b){return g.createComponent(a,b||this)},_onSetFocused:function(a){var b=this.view.getKeyEventTarget()[0];
a?b.focus():b.ownerDocument.activeElement===b&&b.ownerDocument.body.focus()},_onSetX:function(a){this.$el.offset({left:a})},_onSetY:function(a){this.$el.offset({top:a})},_onSetVisible:function(a){this.fire(a?"show":"hide")},show:function(){this.render();this.set("visible",!0);return this},hide:function(){this.set("visible",!1);return this},focus:function(){this.get("focusable")&&this.set("focused",!0)},blur:function(){this.get("focusable")&&this.set("focused",!1)},move:function(a,b){this.set({x:a,
y:b})},handleDblClick:function(a){this.get("disabled")||this.handleDblClickInternal(a)},handleDblClickInternal:function(a){this.handleClickInternal(a)},handleMouseEnter:function(a){this.get("disabled")||this.handleMouseEnterInternal(a)},handleMouseEnterInternal:function(a){this.set("highlighted",!!a)},handleMouseLeave:function(a){this.get("disabled")||this.handleMouseLeaveInternal(a)},handleMouseLeaveInternal:function(a){this.set("active",!1);this.set("highlighted",!a)},handleMouseDown:function(a){this.get("disabled")||
this.handleMouseDownInternal(a)},handleMouseDownInternal:function(a){var b;if(1===a.which||n)if(this.get("activeable")&&this.set("active",!0),this.get("focusable")&&this.focus(),b=a.originalEvent.type.toLowerCase(),!this.get("allowTextSelection")&&(-1!==b.indexOf("mouse")||-1!==b.indexOf("pointer")))b=(b=a.target.nodeName)&&b.toLowerCase(),"input"!==b&&"textarea"!==b&&"button"!==b&&a.preventDefault()},handleMouseUp:function(a){this.get("disabled")||this.handleMouseUpInternal(a)},handleMouseUpInternal:function(a){this.get("active")&&
(1===a.which||n)&&this.set("active",!1)},handleContextMenu:function(a){this.get("disabled")||this.handleContextMenuInternal(a)},handleContextMenuInternal:function(){},handleFocus:function(){this.get("disabled")||this.handleFocusInternal()},handleFocusInternal:function(){this.focus();this.fire("focus")},handleBlur:function(){this.get("disabled")||this.handleBlurInternal()},handleBlurInternal:function(){this.blur();this.fire("blur")},handleKeydown:function(a){if(!this.get("disabled")&&this.handleKeyDownInternal(a))return a.halt(),
!0},handleKeyDownInternal:function(a){if(a.keyCode===k.KeyCode.ENTER)return this.handleClickInternal(a)},handleClick:function(a){this.get("disabled")||this.handleClickInternal(a)},handleClickInternal:function(){this.get("focusable")&&this.focus()},destructor:function(){g.removeComponent(this.get("id"));this.view?this.view.destroy():this.get("srcNode")&&this.get("srcNode").remove()}},{name:"control",ATTRS:{id:{view:1,valueFn:function(){return f.guid("ks-component")}},content:{view:1,value:""},width:{view:1},
height:{view:1},elCls:{view:1,value:[],setter:function(a){"string"===typeof a&&(a=a.split(/\s+/));return a||[]}},elStyle:{view:1,value:{}},elAttrs:{view:1,value:{}},elBefore:{},el:{setter:function(a){this.$el=a;this.el=a[0]}},x:{},y:{},xy:{setter:function(a){var b=f.makeArray(a);b.length&&(void 0!==b[0]&&this.set("x",b[0]),void 0!==b[1]&&this.set("y",b[1]));return a},getter:function(){return[this.get("x"),this.get("y")]}},zIndex:{view:1},render:{},visible:{sync:0,value:!0,view:1},srcNode:{setter:function(a){return k.all(a)}},
handleMouseEvents:{value:!0},focusable:{value:!0,view:1},allowTextSelection:{value:!1},activeable:{value:!0},focused:{view:1},active:{view:1,value:!1},highlighted:{view:1,value:!1},prefixCls:{view:1,value:f.config("component/prefixCls")||"ks-"},prefixXClass:{},parent:{setter:function(a,b){(b=this.get("parent"))&&this.removeTarget(b);a&&this.addTarget(a)}},disabled:{view:1,value:!1},xrender:{value:e},view:{setter:function(a){this.view=a}}}});e.getDefaultRender=h;e.extend=function b(c,d,e){var i=f.makeArray(arguments),
k,n=i[i.length-1];if(k=n.xclass)n.name=k;i=m.extend.apply(this,i);k&&g.setConstructorByXClass(k,i);i.extend=b;i.getDefaultRender=h;return i};return e});
/*
Copyright 2014, KISSY v1.49.10
MIT Licensed
build time: Dec 10 14:48
*/
KISSY.add("component/manager",[],function(){var h=0,e,g={},c={};return e={__instances:c,addComponent:function(a,b){c[a]=b},removeComponent:function(a){delete c[a]},getComponent:function(a){return c[a]},createComponent:function(a,b){var d;if(a){if(!a.isControl&&b&&(a.prefixCls||(a.prefixCls=b.get("prefixCls")),!a.xclass&&a.prefixXClass))a.xclass=a.prefixXClass,a.xtype&&(a.xclass+="-"+a.xtype);if(!a.isControl&&(d=a.xclass))d=e.getConstructorByXClass(d),a=new d(a);a.isControl&&b&&a.setInternal("parent",
b)}return a},getConstructorByXClass:function(a){var a=a.split(/\s+/),b=-1,d,c,f,e=null;for(c=0;c<a.length;c++)if((f=g[a[c]])&&(d=f.priority)>b)b=d,e=f.constructor;return e},setConstructorByXClass:function(a,b){g[a]={constructor:b,priority:h++}}}});
/*
Copyright 2014, KISSY v1.49.10
MIT Licensed
build time: Dec 10 15:07
*/
KISSY.add("xtemplate/runtime/scope",[],function(g){function l(e,f){this.data=e||{};this.affix=f;this.root=this}l.prototype={isScope:1,setParent:function(e){this.parent=e;this.root=e.root},getParent:function(){return this.parent},getRoot:function(){return this.root},set:function(e,f){this.affix||(this.affix={});this.affix[e]=f},setData:function(e){this.data=e},getData:function(){return this.data},mix:function(e){this.affix||(this.affix={});g.mix(this.affix,e)},has:function(e){var f=this.data,i=this.affix;
return i&&e in i?!0:"object"===typeof f&&e in f},get:function(e){var f=this.data,i=this.affix;if(i&&e in i)return i[e];if("object"===typeof f&&e in f)return f[e]},resolve:function(e,f){"."===e&&(e="this");var i=e.split("."),d=this,b,c,a,g,k;if("root"===i[0])i.shift(),d=d.root;else if(f)for(;d&&f--;)d=d.parent;var h=0;for(b=i.length;d;){k=1;a=d;for(c=0;c<b;c++)if(g=i[c],"this"===g)h=1;else if(a===d)if(d.has(g))a=d.get(g),h=1;else{k=0;break}else{if(null==a||"object"!==typeof a||!(g in a)){k=0;break}a=
a[g]}if(k)return a&&a.isScope&&(a=a.data),"function"===typeof a&&(a=a.call(this.data)),[a];if(h)break;d=d.parent}return!1}};return l});
KISSY.add("xtemplate/runtime/commands",["path","./scope"],function(g,l){var e,f=l("path"),i=l("./scope");return e={"debugger":g.noop,each:function(d,b){var c=b.params,a=c[0],e=c[2]||"xindex",c=c[1],f="",h,j,m;if(a)if(j=new i,g.isArray(a)){h=a.length;for(var n=0;n<h;n++)j.data=a[n],m=j.affix={xcount:h},m[e]=n,c&&(m[c]=a[n]),j.setParent(d),f+=b.fn(j)}else for(h in a)j.data=a[h],m=j.affix={},m[e]=h,c&&(m[c]=a[h]),j.setParent(d),f+=b.fn(j);else b.inverse&&(f=b.inverse(d));return f},"with":function(d,
b){var c=b.params[0],a="";c?(c=new i(c),c.setParent(d),a=b.fn(c)):b.inverse&&(a=b.inverse(d));return a},"if":function(d,b){var c="";b.params[0]?b.fn&&(c=b.fn(d)):b.inverse&&(c=b.inverse(d));return c},set:function(d,b){d.mix(b.hash);return""},include:function(d,b){var c=b.params;if(!c||1!==c.length)return"";if(b.hash){var a=new i(b.hash);a.setParent(d);d=a}a=this.config.name;c=c[0];if("."===c.charAt(0)){if("unspecified"===a)return"";c=f.resolve(a,"../",c)}a=this.config.loader.call(this,c);b=g.merge(this.config);
b.name=c;b.commands=this.config.commands;b.macros=this.config.macros;return this.invokeEngine(a,d,b)},macro:function(d,b){var c=b.params,a=c[0],e=c.slice(1),c=this.config.macros;if(b.fn)c[a]||(c[a]={paramNames:e,fn:b.fn});else{var f={},a=c[a];g.each(a.paramNames,function(c,j){f[c]=e[j]});c=new i(f);return a.fn.call(this,c)}return""},parse:function(d,b){return e.include.call(this,new i,b)}}});
KISSY.add("xtemplate/runtime",["./runtime/commands","./runtime/scope"],function(g,l){function e(){}function f(j,c){for(var a=c.split("."),b=j,e=a.length,d=0;d<e&&!(b=b[a[d]],!b);d++);return b}function i(j,c,a,b){var d;if(b=f(j.config.commands,b)){try{d=b.call(j,c,a)}catch(e){}return{find:!0,value:d}}return{find:!1}}function d(j,c,a,b,d){var f,j=j.config.silent?e:g.error,c=c.resolve(a,b);!1===c?j('can not find property: "'+a+'" at line '+d,"warn"):f=c[0];return f}function b(j,a){this.tpl=j;a=g.merge(h,
a);a.commands=g.merge(a.commands,c);a.utils=k;a.macros=a.macros||{};this.config=a}var c=l("./runtime/commands"),a=l("./runtime/scope"),p=g.escapeHtml,k={runBlockCommand:function(a,c,b,d,i){var h=a.config,l=h.silent?e:g.error,h=h.commands,o=f(h,d);if(!o)if(!b.params&&!b.hash){var k=c.resolve(d);!1===k?(l('can not find property: "'+d+'" at line '+i),k=""):k=k[0];o=h["if"];g.isArray(k)?o=h.each:"object"===typeof k&&(o=h["with"]);b.params=[k]}else return"";var q;try{q=o.call(a,c,b)}catch(p){}return q},
renderOutput:function(a,c){void 0===a&&(a="");return c&&a?p(a):a},getProperty:function(a,c,b,e,f){return d(a,c,b,e,f)},runInlineCommand:function(a,c,b,d,e){var f="",a=i(a,c,b,d,e);a.find&&(f=a.value);return f},getPropertyOrRunCommand:function(a,c,b,e,f,g){var h,k=b.hash||b.params,b=i(a,c,b,e,g,k);b.find?h=b.value:k||(h=d(a,c,e,f,g));return h}},h={silent:!0,name:"unspecified",loader:function(a){return g.require(a)}};g.mix(b,{commands:c,utils:k,addCommand:function(a,b){c[a]=b},removeCommand:function(a){delete c[a]}});
b.prototype={constructor:b,invokeEngine:function(a,b,c){return(new this.constructor(a,c)).render(b,!0)},removeCommand:function(a){delete this.config.commands[a]},addCommand:function(a,b){this.config.commands[a]=b},render:function(b){var c=b;if(!c||!c.isScope)c=new a(b);return this.tpl(c,g)}};b.Scope=a;return b});
/*
Copyright 2014, KISSY v1.49.10
MIT Licensed
build time: Dec 10 15:04
*/
KISSY.add("menu/menu-render",["component/container"],function(e,a){return a("component/container").getDefaultRender().extend({beforeCreateDom:function(a){a.elAttrs.role="menu"},containsElement:function(a){var c=this.$el;return c&&(c[0]===a||c.contains(a))}})});
KISSY.add("menu/control",["node","component/container","component/extension/delegate-children","./menu-render"],function(e,a){function b(a){a.target.isMenu&&(a=a.newVal,this.el.setAttribute("aria-activedescendant",a&&a.el.id||""))}var c=a("node"),h=a("component/container"),d=a("component/extension/delegate-children"),g=a("./menu-render"),i=c.KeyCode;return h.extend([d],{isMenu:1,_onSetHighlightedItem:function(a,f){var d;a&&f&&(d=f.prevVal)&&d.set("highlighted",!1,{data:{byPassSetHighlightedItem:1}})},
_onSetVisible:function(a,f){this.callSuper(f);var d;!a&&(d=this.get("highlightedItem"))&&d.set("highlighted",!1)},bindUI:function(){this.on("afterHighlightedItemChange",b,this)},getRootMenu:function(){return this},handleMouseEnterInternal:function(a){this.callSuper(a);if((a=this.getRootMenu())&&a._popupAutoHideTimer)clearTimeout(a._popupAutoHideTimer),a._popupAutoHideTimer=null},handleBlurInternal:function(a){this.callSuper(a);var f;(f=this.get("highlightedItem"))&&f.set("highlighted",!1)},_getNextEnabledHighlighted:function(a,
f){var d=this.get("children"),b=d.length,c=a;do{var g=d[a];if(!g.get("disabled")&&!1!==g.get("visible"))return d[a];a=(a+f+b)%b}while(a!==c)},handleKeyDownInternal:function(a){var f=this.get("highlightedItem");if(f&&f.handleKeyDownInternal(a))return!0;var d=this.get("children"),b=d.length;if(0!==b){var c;switch(a.keyCode){case i.ESC:(f=this.get("highlightedItem"))&&f.set("highlighted",!1);break;case i.HOME:c=this._getNextEnabledHighlighted(0,1);break;case i.END:c=this._getNextEnabledHighlighted(b-
1,-1);break;case i.UP:f?(a=e.indexOf(f,d),b=(a-1+b)%b):b-=1;c=this._getNextEnabledHighlighted(b,-1);break;case i.DOWN:f?(a=e.indexOf(f,d),b=(a+1+b)%b):b=0,c=this._getNextEnabledHighlighted(b,1)}if(c)return c.set("highlighted",!0,{data:{fromKeyboard:1}}),!0}},containsElement:function(a){if(!this.get("visible")||!this.$el)return!1;if(this.view.containsElement(a))return!0;for(var f=this.get("children"),b=0,d=f.length;b<d;b++){var c=f[b];if(c.containsElement&&c.containsElement(a))return!0}return!1}},
{ATTRS:{highlightedItem:{value:null},xrender:{value:g},defaultChildCfg:{value:{xclass:"menuitem"}}},xclass:"menu"})});
KISSY.add("menu/menuitem-render",["component/control"],function(e,a){return a("component/control").getDefaultRender().extend({beforeCreateDom:function(a){a.elAttrs.role=a.selectable?"menuitemradio":"menuitem";a.selected&&a.elCls.push(this.getBaseCssClasses("selected"))},_onSetSelected:function(a){var c=this.getBaseCssClasses("selected");this.$el[a?"addClass":"removeClass"](c)},containsElement:function(a){var c=this.$el;return c&&(c[0]===a||c.contains(a))}},{HTML_PARSER:{selectable:function(a){return a.hasClass(this.getBaseCssClass("selectable"))}}})});
KISSY.add("menu/menuitem",["component/control","./menuitem-render","node"],function(e,a){var b=a("component/control"),c=a("./menuitem-render"),h=a("node").all;return b.extend({isMenuItem:1,handleClickInternal:function(){this.callSuper();this.get("selectable")&&this.set("selected",!0);this.fire("click");return!0},_onSetHighlighted:function(a,c){var b=this.get("parent");if(!c||!c.byPassSetHighlightedItem)this.get("rendered")?b.set("highlightedItem",a?this:null):a&&b.set("highlightedItem",this);if(a){var e=
this.$el;(b=e.parent(function(a){return"visible"!==h(a).css("overflow")},b.get("el").parent()))&&e.scrollIntoView(b,{alignWithTop:!0,allowHorizontalScroll:!0,onlyScrollIfNeeded:!0})}},containsElement:function(a){return this.view.containsElement(a)}},{ATTRS:{focusable:{value:!1},handleMouseEvents:{value:!1},selectable:{view:1},value:{},selected:{view:1},xrender:{value:c}},xclass:"menuitem"})});
KISSY.add("menu/check-menuitem-xtpl",["component/extension/content-xtpl"],function(e,a,b,c){return function(b){var d,g;d=this.config.utils;"undefined"!==typeof c&&c.kissy&&(g=c);var e=d.renderOutput,j=d.runInlineCommand;d='<div class="';var f={},k=[];k.push("checkbox");f.params=k;f=j(this,b,f,"getBaseCssClasses",1);d+=e(f,!0);d+='">\n</div>\n';f={};k=[];k.push("component/extension/content-xtpl");f.params=k;g&&(a("component/extension/content-xtpl"),f.params[0]=g.resolveByName(f.params[0]));b=j(this,
b,f,"include",3);return d+=e(b,!1)}});KISSY.add("menu/check-menuitem-render",["./menuitem-render","component/extension/content-render","./check-menuitem-xtpl"],function(e,a){var b=a("./menuitem-render"),c=a("component/extension/content-render"),h=a("./check-menuitem-xtpl");return b.extend([c],{beforeCreateDom:function(a){a.checked&&a.elCls.push(this.getBaseCssClasses("checked"))},_onSetChecked:function(a){var b=this.getBaseCssClasses("checked");this.$el[a?"addClass":"removeClass"](b)}},{ATTRS:{contentTpl:{value:h}}})});
KISSY.add("menu/check-menuitem",["./menuitem","./check-menuitem-render"],function(e,a){var b=a("./menuitem"),c=a("./check-menuitem-render");return b.extend({handleClickInternal:function(){this.callSuper();this.set("checked",!this.get("checked"));this.fire("click");return!0}},{ATTRS:{checked:{view:1},xrender:{value:c}},xclass:"check-menuitem"})});
KISSY.add("menu/submenu-xtpl",[],function(){return function(e){var a;a=this.config.utils;var b=a.renderOutput,c=a.runInlineCommand,h=a.getPropertyOrRunCommand;a='<div id="ks-content-';var d=h(this,e,{},"id",0,1);a+=b(d,!0);a+='"\n     class="';var d={},g=[];g.push("content");d.params=g;c=c(this,e,d,"getBaseCssClasses",2);a+=b(c,!0);a+='">';c=h(this,e,{},"content",0,2);a+=b(c,!1);a+='</div>\n<span class="';e=h(this,e,{},"prefixCls",0,3);a+=b(e,!0);return a+'submenu-arrow">\u25ba</span>'}});
KISSY.add("menu/submenu-render",["./submenu-xtpl","./menuitem-render","component/extension/content-render"],function(e,a){var b=a("./submenu-xtpl"),c=a("./menuitem-render"),h=a("component/extension/content-render");return c.extend([h],{decorateDom:function(a){var b=this.control,c=b.get("prefixCls"),a=a.one("."+c+"popupmenu"),e=a[0].ownerDocument.body;e.insertBefore(a[0],e.firstChild);e=this.getComponentConstructorByNode(c,a);b.setInternal("menu",new e({srcNode:a,prefixCls:c}))}},{ATTRS:{contentTpl:{value:b}}})});
KISSY.add("menu/submenu",["node","./menuitem","./submenu-render"],function(e,a){function b(a){var b=a.target;b!==this&&b.isMenuItem&&a.newVal&&(this.clearHidePopupMenuTimers(),this.get("highlighted")||(this.set("highlighted",!0),b.set("highlighted",!1),b.set("highlighted",!0)))}function c(){var a=this.get("menu"),b={node:this.$el,points:["tr","tl"],overflow:{adjustX:1,adjustY:1}};e.mix(a.get("align"),b,!1);a.show();this.el.setAttribute("aria-haspopup",a.get("el").attr("id"))}function h(){this.get("menu").hide()}
var d=a("node"),g=a("./menuitem"),i=a("./submenu-render"),j=d.KeyCode;return g.extend({isSubMenu:1,clearShowPopupMenuTimers:function(){var a;if(a=this._showTimer)a.cancel(),this._showTimer=null},clearHidePopupMenuTimers:function(){var a;if(a=this._dismissTimer)a.cancel(),this._dismissTimer=null},clearSubMenuTimers:function(){this.clearHidePopupMenuTimers();this.clearShowPopupMenuTimers()},bindUI:function(){this.on("afterHighlightedChange",b,this)},handleMouseLeaveInternal:function(){this.set("highlighted",
!1,{data:{fromMouse:1}});this.clearSubMenuTimers();this.get("menu").get("visible")&&(this._dismissTimer=e.later(h,1E3*this.get("menuDelay"),!1,this))},handleMouseEnterInternal:function(){this.set("highlighted",!0,{data:{fromMouse:1}});this.clearSubMenuTimers();this.get("menu").get("visible")||(this._showTimer=e.later(c,1E3*this.get("menuDelay"),!1,this))},_onSetHighlighted:function(a,b){b&&(this.callSuper(b),b.fromMouse||(a&&!b.fromKeyboard?c.call(this):a||h.call(this)))},handleClickInternal:function(){c.call(this);
this.callSuper()},handleKeyDownInternal:function(a){var b=this.get("menu"),d,e=b.get("visible"),g=a.keyCode;if(e){if(!b.handleKeyDownInternal(a))if(g===j.LEFT)this.set("highlighted",!1),this.set("highlighted",!0,{data:{fromKeyboard:1}});else return}else if(g===j.RIGHT)c.call(this),a=b.get("children"),(d=a[0])&&d.set("highlighted",!0,{data:{fromKeyboard:1}});else{if(g===j.ENTER)return this.handleClickInternal(a);return}return!0},containsElement:function(a){return this.get("menu").containsElement(a)},
destructor:function(){var a=this.get("menu");this.clearSubMenuTimers();a.destroy()}},{ATTRS:{menuDelay:{value:0.15},menu:{value:{},getter:function(a){a.isControl||(a.xclass=a.xclass||"popupmenu",a=this.createComponent(a),this.setInternal("menu",a));return a},setter:function(a){a.isControl&&a.setInternal("parent",this)}},xrender:{value:i}},xclass:"submenu"})});
KISSY.add("menu/popupmenu-render",["component/extension/content-render","./menu-render"],function(e,a){var b=a("component/extension/content-render");return a("./menu-render").extend([b])});
KISSY.add("menu/popupmenu",["component/extension/align","component/extension/shim","./control","./popupmenu-render"],function(e,a){var b=a("component/extension/align"),c=a("component/extension/shim"),h=a("./control"),d=a("./popupmenu-render");return h.extend([c,b],{getRootMenu:function(){var a=this,b;do b=a,a=a.get("parent");while(a&&(a.isMenuItem||a.isMenu));return b===this?null:b},handleMouseLeaveInternal:function(a){this.callSuper(a);if(this.get("autoHideOnMouseLeave")){var b=this.getRootMenu();
b&&(clearTimeout(b._popupAutoHideTimer),b._popupAutoHideTimer=setTimeout(function(){var a;(a=b.get("highlightedItem"))&&a.set("highlighted",!1)},1E3*this.get("parent").get("menuDelay")))}},isPopupMenu:1,handleBlurInternal:function(a){this.callSuper(a);this.hide()}},{ATTRS:{focusable:{value:!1},autoHideOnMouseLeave:{},contentEl:{},visible:{value:!1},xrender:{value:d}},xclass:"popupmenu"})});
KISSY.add("menu",["menu/control","menu/menuitem","menu/check-menuitem","menu/submenu","menu/popupmenu"],function(e,a){var b=a("menu/control"),c=a("menu/menuitem"),h=a("menu/check-menuitem"),d=a("menu/submenu"),g=a("menu/popupmenu");b.Item=c;b.CheckItem=h;b.SubMenu=d;b.PopupMenu=g;return b});
/*
Copyright 2014, KISSY v1.49.10
MIT Licensed
build time: Dec 10 14:47
*/
KISSY.add("component/container/render",["component/control","component/manager"],function(g,d){var f=d("component/control"),i=d("component/manager");return f.getDefaultRender().extend([],{decorateDom:function(){var d=this,f=d.getChildrenContainerEl(),a=d.control,b=a.get("defaultChildCfg"),c=b.prefixCls,e=b.xclass,h=[];f.children().each(function(a){var f=d.getComponentConstructorByNode(c,a)||e&&i.getConstructorByXClass(e);f&&h.push(new f(g.merge(b,{srcNode:a})))});a.set("children",h)},getChildrenContainerEl:function(){return this.$el}},
{name:"ContainerRender"})});
KISSY.add("component/container",["component/control","./container/render"],function(g,d){function f(a){if(a.target===this){var b=a.component,c=this.get("children"),a=a.index;c.splice(a,0,b);c=this.get("children");b=c[a];b.setInternal("parent",this);this.get("rendered")&&this.renderChild(a);this.fire("afterAddChild",{component:b,index:a})}}function i(a){if(a.target===this){var b=a.component,c,e,h=a.destroy,d=this.get("children"),a=a.index;-1!==a&&d.splice(a,1);b.setInternal("parent",null);if(h)b.destroy&&
b.destroy();else if(b.get&&(e=b.el))(c=e.parentNode)&&c.removeChild(e);this.fire("afterRemoveChild",{component:b,index:a})}}var j=d("component/control"),k=d("./container/render");return j.extend({isContainer:!0,initializer:function(){var a=this.get("prefixCls"),b=this.get("defaultChildCfg");this.publish("beforeAddChild",{defaultFn:f});this.publish("beforeRemoveChild",{defaultFn:i});b.prefixCls=b.prefixCls||a},createDom:function(){this.createChildren()},renderUI:function(){this.renderChildren()},renderChildren:function(){var a,
b=this.get("children");for(a=0;a<b.length;a++)this.renderChild(a)},createChildren:function(){var a,b=this.get("children");for(a=0;a<b.length;a++)this.createChild(a)},addChild:function(a,b){var c=this.get("children");void 0===b&&(b=c.length);this.fire("beforeAddChild",{component:a,index:b})},renderChild:function(a){var b=this.get("children");this.createChild(a).render();this.fire("afterRenderChild",{component:b[a],index:a})},createChild:function(a){var b,c,e,d;b=this.get("children")[a];d=this.view.getChildrenContainerEl();
e=d[0];c=e.children[a]||null;b.get("rendered")?(d=b.el,d.parentNode!==e&&e.insertBefore(d,c)):(c?b.set("elBefore",c):b.set("render",d),b.create());this.fire("afterCreateChild",{component:b,index:a});return b},removeChild:function(a,b){void 0===b&&(b=!0);this.fire("beforeRemoveChild",{component:a,index:g.indexOf(a,this.get("children")),destroy:b})},removeChildren:function(a){var b,c=[].concat(this.get("children"));for(b=0;b<c.length;b++)this.removeChild(c[b],a);return this},getChildAt:function(a){return this.get("children")[a]||
null},destructor:function(){var a,b=this.get("children");for(a=0;a<b.length;a++)b[a].destroy&&b[a].destroy()}},{ATTRS:{children:{value:[],getter:function(a){var b=null,c,d;for(c=0;c<a.length;c++)d=a[c],d.isControl||(b=b||this.get("defaultChildCfg"),g.mix(d,b,!1),a[c]=this.createComponent(d));return a},setter:function(a){var b,c;for(b=0;b<a.length;b++)c=a[b],c.isControl&&c.setInternal("parent",this)}},defaultChildCfg:{value:{}},xrender:{value:k}},name:"container"})});
/*
Copyright 2014, KISSY v1.49.10
MIT Licensed
build time: Dec 10 14:48
*/
KISSY.add("component/extension/delegate-children",["node","component/manager"],function(d,e){function h(a){a.target===this&&a.component.$el.addClass(this.__childClsTag)}function i(a){a.target===this&&(a=a.component.$el)&&a.removeClass(this.__childClsTag)}function f(){this.__childClsTag=d.guid("ks-component-child");this.on("afterRenderChild",h,this).on("afterRemoveChild",i,this)}var j=e("node"),k=e("component/manager"),g=d.UA.ieMode,c=j.Gesture;d.Features.isTouchEventSupported();d.augment(f,{handleChildrenEvents:function(a){if(!this.get("disabled")){var b=
this.getOwnerControl(a);if(b&&!b.get("disabled"))switch(a.stopPropagation(),a.type){case c.start:b.handleMouseDown(a);break;case c.end:b.handleMouseUp(a);break;case c.tap:b.handleClick(a);break;case "mouseenter":b.handleMouseEnter(a);break;case "mouseleave":b.handleMouseLeave(a);break;case "contextmenu":b.handleContextMenu(a);break;case "dblclick":b.handleDblClick(a)}}},__bindUI:function(){var a=c.start+" "+c.end+" "+c.tap;c.cancel&&(a+=" "+c.cancel);a+=" mouseenter mouseleave contextmenu "+(g&&9>
g?"dblclick ":"");this.$el.delegate(a,"."+this.__childClsTag,this.handleChildrenEvents,this)},getOwnerControl:function(a){return k.getComponent(a.currentTarget.id)}});return f});
/*
Copyright 2014, KISSY v1.49.10
MIT Licensed
build time: Dec 10 14:48
*/
KISSY.add("component/extension/content-render",["component/extension/content-xtpl"],function(e,g){function f(a){var b=a.control,c=b.get("contentEl");a.$contentEl=b.$contentEl=c;a.contentEl=b.contentEl=c[0]}function d(){}var h=g("component/extension/content-xtpl");d.prototype={__beforeCreateDom:function(a,b){e.mix(b,{contentEl:"#ks-content-{id}"})},__createDom:function(){f(this)},__decorateDom:function(){f(this)},getChildrenContainerEl:function(){return this.control.get("contentEl")},_onSetContent:function(a){var b=
this.control,c=b.$contentEl;c.html(a);b.get("allowTextSelection")||c.unselectable()}};e.mix(d,{ATTRS:{contentTpl:{value:h}},HTML_PARSER:{content:function(a){return a.one("."+this.getBaseCssClass("content")).html()},contentEl:function(a){return a.one("."+this.getBaseCssClass("content"))}}});return d});
/*
Copyright 2014, KISSY v1.49.10
MIT Licensed
build time: Dec 10 14:48
*/
KISSY.add("component/extension/content-xtpl",[],function(){return function(b){var a;a=this.config.utils;var d=a.renderOutput,e=a.runInlineCommand,f=a.getPropertyOrRunCommand;a='<div id="ks-content-';var c=f(this,b,{},"id",0,1);a+=d(c,!0);a+='"\n           class="';var c={},g=[];g.push("content");c.params=g;e=e(this,b,c,"getBaseCssClasses",2);a+=d(e,!0);a+='">';b=f(this,b,{},"content",0,2);a+=d(b,!1);return a+"</div>"}});
/*
Copyright 2014, KISSY v1.49.10
MIT Licensed
build time: Dec 10 14:48
*/
KISSY.add("component/extension/align",["node"],function(k,u){function m(a){var c=a.ownerDocument.body,d=j(a).css("position");if(!("fixed"===d||"absolute"===d))return"html"===a.nodeName.toLowerCase()?null:a.parentNode;for(a=a.parentNode;a&&a!==c;a=a.parentNode)if(d=j(a).css("position"),"static"!==d)return a;return null}function n(a){var c,d,b={left:0,right:Infinity,top:0,bottom:Infinity},f;f=a.ownerDocument;d=j(f).getWindow();c=f.body;for(f=f.documentElement;a=m(a);)if((!v.ie||0!==a.clientWidth)&&
a!==c&&a!==f&&"visible"!==j(a).css("overflow")){var h=j(a).offset();h.left+=a.clientLeft;h.top+=a.clientTop;b.top=Math.max(b.top,h.top);b.right=Math.min(b.right,h.left+a.clientWidth);b.bottom=Math.min(b.bottom,h.top+a.clientHeight);b.left=Math.max(b.left,h.left)}f=d.scrollLeft();a=d.scrollTop();b.left=Math.max(b.left,f);b.top=Math.max(b.top,a);c=d.width();d=d.height();b.right=Math.min(b.right,f+c);b.bottom=Math.min(b.bottom,a+d);return 0<=b.top&&0<=b.left&&b.bottom>b.top&&b.right>b.left?b:null}function o(a,
c,d,b){var f,h;f=a.left;h=a.top;c=p(c,d[0]);a=p(a,d[1]);a=[a.left-c.left,a.top-c.top];return{left:f-a[0]+ +b[0],top:h-a[1]+ +b[1]}}function q(a,c,d){var b=[];k.each(a,function(a){b.push(a.replace(c,function(a){return d[a]}))});return b}function l(){}function r(a){var c,d;c=a[0];k.isWindow(c)?(a=j(c).getWindow(),c={left:a.scrollLeft(),top:a.scrollTop()},d=a.width(),a=a.height()):(c=a.offset(),d=a.outerWidth(),a=a.outerHeight());c.width=d;c.height=a;return c}function p(a,c){var d=c.charAt(0),b=c.charAt(1),
f=a.width,h=a.height,e,g;e=a.left;g=a.top;"c"===d?g+=h/2:"b"===d&&(g+=h);"c"===b?e+=f/2:"r"===b&&(e+=f);return{left:e,top:g}}function w(a){a.target===this&&a.newVal&&this._onSetAlign(this.get("align"))}function s(){this.get("visible")&&this._onSetAlign(this.get("align"))}var t=u("node"),x=k.Env.host,j=t.all,v=k.UA;l.__getOffsetParent=m;l.__getVisibleRectForElement=n;l.ATTRS={align:{value:{}}};l.prototype={__bindUI:function(){this.on("beforeVisibleChange",w,this);this.$el.getWindow().on("resize",s,
this)},_onSetAlign:function(a){a&&a.points&&this.align(a.node,a.points,a.offset,a.overflow)},align:function(a,c,d,b){var a=t.one(a||x),d=d&&[].concat(d)||[0,0],b=b||{},f=this.$el,h=0,e=n(f[0]),g=r(f),j=r(a),a=o(g,j,c,d),i=k.merge(g,a);if(e&&(b.adjustX||b.adjustY)){if(a.left<e.left||a.left+g.width>e.right)h=1,c=q(c,/[lr]/ig,{l:"r",r:"l"}),d[0]=-d[0];if(a.top<e.top||a.top+g.height>e.bottom)h=1,c=q(c,/[tb]/ig,{t:"b",b:"t"}),d[1]=-d[1];h&&(a=o(g,j,c,d),k.mix(i,a));c=b.adjustX&&(a.left<e.left||a.left+
g.width>e.right);b=b.adjustY&&(a.top<e.top||a.top+g.height>e.bottom);if(c||b)a=k.clone(a),i={width:g.width,height:g.height},c&&a.left<e.left&&(a.left=e.left),c&&a.left+i.width>e.right&&(a.left=Math.max(e.right-i.width,e.left)),b&&a.top<e.top&&(a.top=e.top),b&&a.top+i.height>e.bottom&&(a.top=Math.max(e.bottom-i.height,e.top)),i=k.mix(a,i)}this.set({x:i.left,y:i.top},{force:1});i.width!==g.width&&this.set("width",f.width()+i.width-g.width);i.height!==g.height&&this.set("height",f.height()+i.height-
g.height);return this},center:function(a){this.set("align",{node:a,points:["cc","cc"],offset:[0,0]});return this},__destructor:function(){this.$el&&this.$el.getWindow().detach("resize",s,this)}};return l});
/*
Copyright 2014, KISSY v1.49.10
MIT Licensed
build time: Dec 10 14:48
*/
KISSY.add("component/extension/shim",[],function(a){function b(){}var a=6===a.UA.ie,c='<iframe style="position: absolute;border: none;width: '+(a?"expression(this.parentNode.clientWidth)":"100%")+";top: 0;opacity: 0;filter: alpha(opacity=0);left: 0;z-index: -1;height: "+(a?"expression(this.parentNode.clientHeight)":"100%")+';"/>';b.ATTRS={shim:{value:a}};b.prototype.__createDom=function(){this.get("shim")&&this.get("el").prepend(c)};return b});
